---
# Initialize Linux Hosts

# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Initialize Hosts for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: init-hosts.yml
  tags: install

#
- name: Install for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: install.yml
  tags: install

#
- name: Install for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: ssh_gpadmin_user.yml
  tags: install

#
- name: Install for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: ssh_root_user.yml
  tags: install

#
- name: Uninstall for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: uninstall.yml
  tags: uninstall

