ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

gpcc:
  base_dir: "/usr/local"
  prefix_dir: "greenplum-cc"
  major_version: 6
  minor_version: 10
  patch_version: 0
  metric_arch: 'x86_64'
  os_name: 'rhel9'
  gpccws_port: 28080
  gpmon_password: "changeme"
  ssl_dir: "/home/gpadmin/certs"
  ssl_days: 3660
  ssl_country: "KR"
  ssl_state: "Seoul"
  ssl_location: "GangNam"
  ssl_organization: "Pivotal"
  ssl_common_name: "jtest.pivotal.io"
  ssl_email: "jomoon@pivotal.io"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


gpdb:
  cluster_name: jack-kr-gpdb
  base_dir: "/usr/local"
  admin_user: "gpadmin"
  admin_passwd: "changeme"
  admin_home_dir: "/home/gpadmin"
  master_data_dir: "/data/master/gpseg-1"
  coordinator_data_dir: "/data/master/gpseg-1"
  # coordinator_data_dir: "/data/coordinator/gpseg-1"
  data_dir: "/data"
  package_name: "greenplum-db"
  pkg_name: "greenplum-db"
  major_version: 6
  minor_version: 26
  patch_version: 1
  build_version: 1
  os_name: 'rhel9'
  arch_name: 'x86_64'
  binary_type: 'rpm'
  number_segments: 4
  mirror_enable: true
  spread_mirrors: ""
  initdb_single: False
  initdb_with_standby: True
  seg_serialized_install: False
  domain: "jtest.pivotal.io"
  repo_url: ""
  download_url: ""
  download: false
  base_path: /root
  host_num: "{{ groups['all'] | length }}"
  cgroup: v1
  metric_major_version: 6
  metric_minor_version: 26.0
  metric_build_version:
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"
  client:
    net:
      type: "virtual"              # Or Physical
      cores: 1
      ipaddr0: "192.168.0.6"
      ipaddr1: "192.168.1.6"
      ipaddr2: "192.168.2.6"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1."
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05" ]
  debug_opt: ""  # --debug


jdk:
  oss:
    install: true
    jvm_home: "/usr/lib/jvm"
    major_version: 1
    minor_version: 8
    patch_version: 0
    # 1.8.0
    # 11.0.4
    # 17.0.2
  oracle:
    install: false
    jvm_home: "/usr/lib/jvm"
    major_version: 13
    minor_version: 0
    patch_version: 2
    download: false


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

