---

#
- name: Install EPEL repo.
  become: true
  yum:
    name: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-{{ ansible_distribution_major_version }}-14.noarch.rpm
    state: present
    disable_gpg_check: true
  register: epel_repo_installed

#
- name: Print EPEL repo installed
  become: true
  debug: msg={{ epel_repo_installed }}

#
- name: Install R
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: r_installed
  with_items:
    - "https://cdn.rstudio.com/r/centos-{{ ansible_distribution_major_version }}/pkgs/R-{{ r_major_version }}.{{ r_minor_version }}.{{ r_patch_version }}-1-1.x86_64.rpm"
    # - "https://cdn.rstudio.com/r/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}/pkgs/R-{{ r_major_version }}.{{ r_minor_version }}.{{ r_patch_version }}-1-1.x86_64.rpm"

#
- name: Print R installed
  become: true
  debug: msg={{ r_installed }}

#
- name: Verify R version
  become: true
  command: /opt/R/{{ r_major_version }}.{{ r_minor_version }}.{{ r_patch_version }}/bin/R --version
  register: r_version_verified

#
- name: Print R version
  become: true
  debug: msg={{ r_version_verified }}

#
- name: Create symbolic links to the version of R
  become: true
  file:
    src: /opt/R/{{ r_major_version }}.{{ r_minor_version }}.{{ r_patch_version }}/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  register: r_symbolic_links_created
  with_items:
    - "R"
    - "Rscript"

#
- name: Print the symbolic links of R installed
  become: true
  debug: msg={{ r_symbolic_links_created }}

#
# RSPM_SERVER_VERSION=2023.04.0-6
# curl -o rspm -f https://cdn.posit.co/package-manager/linux/amd64/rspm-cli-linux-${RSPM_SERVER_VERSION}
# chmod +x rspm
# rspm list requirements --help
# rspm list requirements --repo=cran --packages=ggplot2,plumber --distribution=ubuntu --release=18.04
# rspm list requirements --repo=validated-subset --packages=* --distribution=ubuntu --release=18.04
