---
# Install or Uninstall R
# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'

#
- name: Install R
  import_tasks: install-r.yml
  tags: install
  when: use_r == true

#
- name: Configure R variables for GPDB
  import_tasks: config-r-variable-gpdb.yml
  tags: config
  when: use_r == true

#
- name: Install R Studio
  import_tasks: install-r-studio.yml
  tags: install
  when: use_r_studio == true

#
- name: Uninstall R
  import_tasks: uninstall-r.yml
  tags: uninstall
  when: use_r == true

#
- name: Unconfigure R variables for GPDB
  import_tasks: unconfig-r-variable-gpdb.yml
  tags: unconfig
  when: use_r == true

#
- name: Uninstall R Studio
  import_tasks: uninstall-r-studio.yml
  tags: uninstall
  when: use_r_studio == true
