
#
- name: Delete lines of R variables in "$GPHOME"/greenplum_path.sh
  become: true
  lineinfile:
    dest: /usr/local/greenplum-db/greenplum_path.sh
    regexp: '^(export )(?!#)(.*R_HOME_DIR.*)'
    state: absent

#
- name: Uncomment the lines of R variables commented by ansible playbook of R
  become: true
  replace:
    path: /usr/local/greenplum-db/greenplum_path.sh
    regexp: '^#(?!#)(.*GPHOME/ext/R-.*)'
    replace: '\1'

#
- name: Recursively change ownership of R libraary directory for root user
  become: true
  file:
    path: /opt/R/{{ r_major_version }}.{{ r_minor_version }}.{{ r_patch_version }}/lib/R/{{ item }}
    state: directory
    recurse: yes
    owner: root
    group: root
  with_items:
    - "doc"
    - "library"
  when: with_gpdb == true
