- hosts: all
  become: true
  gather_facts: true
  roles:
    - { role: gpss }
#    - { role: gpdb }                 # Need to check if get_facts: true is required
#    - { role: init-hosts }
#    - { role: madlib }
#    - { role: postgis }
#    - { role: plr }
#    - { role: init-hosts }
#    - { role: gpdb }                 # Need to check if get_facts: true is required
#    - { role: gptext }
#    - { role: plcontainer }
#    - { role: DataSciencePython }
#    - { role: DataScienceR }
#    - { role: pljava }
#    - { role: plr }
#    - { role: pxf }
#    - { role: gpupgrade }

#- hosts: rh8-master,rh8-slave
#  become: true
#  become_user: gpadmin
#  roles:
#    - { role: gpcc }

#- hosts: rk9-minio
#  become: true
#  gather_facts: true
#  vars:
#    use_nginx: true
#    minio_download: false
#  roles:
#    - { role: minio }                 # Need to check if get_facts: true is required
