- hosts: all
  become: true
  roles:
    - { role: gpdb }                 # Need to check if get_facts: true is required
#    - { role: gptext }
#    - { role: init-hosts }
#   - { role: gpss }
#   - { role: plcontainer }
#   - { role: DataSciencePython }
#   - { role: DataScienceR }
#   - { role: pljava }
#   - { role: plr }
#   - { role: pxf }
#   - { role: gpupgrade }
#   - { role: madlib }               # Failed on ubuntu 18.04
#   - { role: postgis }
#   - { role: plr }

#
#- hosts: rh7-master,rh7-slave
#  become: true
#  become_user: gpadmin
#  roles:
#    - { role: gpcc }
