#- hosts: rh7-master,rh7-slave
#  become: true
#  become_user: gpadmin
#  roles:
#    - { role: gpcc }

- hosts: all
  become: true
  gather_facts: no
  roles:
    - { role: gpdb }               # Need to check if gather_facts: no is required
#    - { role: gptext }
#    - { role: init-hosts }
#   - { role: gpss }
#   - { role: plr }
#   - { role: plcontainer }
#   - { role: pxf }
#   - { role: gpupgrade }
#   - { role: madlib }            # Failed on ubuntu 18.04
#   - { role: postgis }
#   - { role: pljava }
#   - { role: DataSciencePython }
#   - { role: DataScienceR }
