#
- hosts: rh8-master,rh8-slave
  become: true
  become_user: gpadmin
  roles:
    - { role: gpcc }

#
- hosts: all
  become: true
  gather_facts: true
  roles:
    - { role: gpdb }                 # Need to check if get_facts: true is required
    - { role: init-hosts }
#    - { role: plcontainer }
#    - { role: DataScienceR }
#    - { role: DataSciencePython }
#    - { role: gptext }
#    - { role: pljava }
#    - { role: plr }
#    - { role: postgis }
#    - { role: madlib }               # Failed on ubuntu 18.04
#    - { role: pxf }
#    - { role: init-hosts }
#    - { role: gpss }
#    - { role: gpdb }                 # Need to check if get_facts: true is required
#    - { role: gpupgrade }

#- hosts: rk9-minio
#  become: true
#  gather_facts: true
#  vars:
#    use_nginx: true
#    minio_download: false
#  roles:
#    - { role: minio }                 # Need to check if get_facts: true is required
