#- hosts: rh7-master,rh7-slave
#  become: true
#  become_user: gpadmin
#  roles:
#    - { role: gpcc }

#
- hosts: all
  become: true
  gather_facts: true
  roles:
    - { role: gpdb }               # Need to check if gather_facts: no is required
#    - { role: gpss }
#    - { role: init-hosts }               # Need to check if gather_facts: no is required
#    - { role: madlib }             # Failed on ubuntu 18.04
#    - { role: plr }
#   - { role: postgis }
#   - { role: gptext }
#   - { role: plcontainer }
#   - { role: pxf }
#   - { role: gpupgrade }
#   - { role: pljava }
#   - { role: DataSciencePython }
#   - { role: DataScienceR }

#- hosts: rk9-minio
#  become: true
#  gather_facts: true
#  vars:
#    use_nginx: true
#    minio_download: false
#  roles:
#    - { role: minio }               # Need to check if gather_facts: no is required

