---

# Uninstall OSS GPDB on Red Hat / CentOS

# 1
- name: Stop demo cluster
  become: yes
  become_user: gpadmin
  shell: ( cd /home/gpadmin/gpdb ; . /home/gpadmin/greenplum-db/greenplum_path.sh && . /home/gpadmin/gpdb/gpAux/gpdemo/gpdemo-env.sh && gpstop -a )
  async: 180
  poll: 5
  ignore_errors: yes

# 2
- name: Uninstall extra Python modules to prepare development for gpdb
  become: yes
  pip:
    executable: pip2
    requirements: /home/gpadmin/gpdb/python-dependencies.txt
    state: absent
  ignore_errors: yes
#    # extra_args: -i https://example.com/pypi/simple


# 3
#  become_user: gpadmin
- name: Delete gpdb installation and data directory
  become: yes
  shell: ( rm -rf /home/gpadmin/gpdb /home/gpadmin/gp-xerces /home/gpadmin/greenplum-db )
  async: 180
  poll: 5


# 3
- name: Delete line of Change base directory into devtoolset to use higher version of gcc, g++
  become: yes
  become_user: gpadmin
  lineinfile:
    dest: "/home/gpadmin/.bashrc"
    regexp: "{{ item.regexp }}"
    state: "{{ item.state }}"
  with_items:
    - { regexp: 'source scl_source', line: 'source scl_source', state: absent }

# 4
- name: Apply new variables in .bashrc
  become: yes
  become_user: gpadmin
  shell: ( source ~/.bashrc )


# 5
- name: Unintall packages from "Development tools" group and toolchain to use higher version of gcc,g++
  become: yes
  yum:
    name: "{{ item }}"
    state: absent
  async: 120
  poll: 5
  with_items:
    - "centos-release-scl"
    - "devtoolset-7-toolchain"
    - "python-devel"
    - "python2-psutil"
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ( ansible_distribution_major_version is version_compare('8', '<') )

# 6
- name: Uninstall rpm packages in Development tools group
  become: yes
  yum:
    name: ["@Development tools"]
    state: absent
  async: 320
  poll: 5

# 8
- name: Uninstall setuptools pip module
  become: yes
  pip:
    name: setuptools
    executable: pip2
    state: absent
  ignore_errors: yes
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ( ansible_distribution_major_version is version_compare('8', '<=') )

# 8
- name: Uninstall setuptools pip module
  become: yes
  pip:
    name: setuptools
    executable: pip3
    state: absent
  ignore_errors: yes
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ( ansible_distribution_major_version is version_compare('9', '>=') )


# 9
- name: Uninstall rpm pakcages from epel-release repostiory
  become: yes
  yum:
    name: "{{ item }}"
    state: absent
  ignore_errors: yes
  async: 120
  poll: 5
  with_items:
    - "apr-devel"
    - "bison"
    - "bzip2-devel"
    - "cmake3"
    - "flex"
    - "gcc"
    - "gcc-c++"
    - "krb5-devel"
    - "libcurl-devel"
    - "libevent-devel"
    - "libkadm5"
    - "libyaml-devel"
    - "libxml2-devel"
    - "libzstd-devel"
    - "openssl-devel"
    - "perl-ExtUtils-Embed"
    - "readline-devel"
    - "xerces-c-devel"
    - "zlib-devel"
    - "postgresql"
    - "postgresql-devel"
    - "PyYAML"

- name: Uninstall rpm pakcages from epel-release repostiory for lower versions that {{ ansible_distribution }} 8
  become: yes
  yum:
    name: "{{ item }}"
    state: absent
  ignore_errors: yes
  async: 120
  poll: 5
  with_items:
    - "python3"
    - "python3-devel"
    - "python3-pip"
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ( ansible_distribution_major_version is version_compare('8', '<') )

- name: Uninstall python3-libs only for {{ ansible_distribution }} 7
  become: yes
  yum:
    name: "{{ item }}"
    state: absent
  async: 120
  poll: 5
  with_items:
    - "python3-libs"
    - "python-setuptools"
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ( ansible_distribution_major_version is version_compare('7', '==') )

# 10
- name: Uninstall epel-release package
  become: yes
  yum:
    name: epel-release
    state: absent
  async: 120
  poll: 5

