---
#
# Install / Uninstall Greenplum Streaming Server v1.x

# for now fail if it's not a Red Hat based system
- name: Check OS (PGCC v2)
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'

#
- name: Setup Kafka
  import_tasks: setup-kafka.yml
  tags: install

#
- name: Setup GPSS
  import_tasks: setup-gpss.yml
  tags: install

#
- name: Uninstall GPSS
  import_tasks: uninstall-gpss.yml
  tags: uninstall

#
- name: Uninstall Kafka
  import_tasks: uninstall-kafka.yml
  tags: uninstall
