---
#
# Install Greenplum Streaming Server on both GPDB Master and Kafka Broker
# Configure data loading with sample data between them
- name: Check if the GPDB software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed
  when: inventory_hostname in groups['master']

#
- name: Stop if GPDB software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when:
    - inventory_hostname in groups['master']
    - gpdb_installed.stat.exists != True

#
- name: Verify that database is up and running
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -c "SELECT VERSION()" )
  register: select_version
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

#
- set_fact:
    gppkg_install_cmd: "gppkg -a install"
    check_gpss_installed: "gppkg query | grep gpss | awk '{print $1}' | sed 's/[0-9]*//g' | sed 's/.$//g'"
    gpss_package_name: gpss-{{ gpss_gpdb_version }}-{{ gpss_major_version }}.{{ gpss_minor_version }}{{ gpss_patch_version }}-{{ gpss_os_version_gpdb }}-{{ gpss_arch_type }}.gppkg
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ( gpss_gpdb_version|regex_replace('[^0-9]','')|int >= 7 and gpss_os_version_gpdb|regex_replace('[^0-9]','')|int >= 8 )

#
- set_fact:
    gppkg_install_cmd: "gppkg -i"
    check_gpss_installed: "gppkg -q --all | grep gpss | cut -d . -f 1 | sed 's/[0-9]$//g'"
    gpss_package_name: gpss-{{ gpss_gpdb_version }}-{{ gpss_major_version }}.{{ gpss_minor_version }}-{{ gpss_os_version_gpdb }}-{{ gpss_arch_type }}.gppkg
  when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" ) and ( gpss_gpdb_version|regex_replace('[^0-9]','')|int <= 6 and gpss_os_version_gpdb|regex_replace('[^0-9]','')|int <= 8 )

#
- set_fact:
    gppkg_install_cmd: "gppkg -a install"
    check_gpss_installed: "gppkg query | grep gpss | awk '{print $1}' | sed 's/[0-9]*//g' | sed 's/.$//g'"
    gpss_package_name: gpss-{{ gpss_gpdb_version }}-{{ gpss_major_version }}.{{ gpss_minor_version }}{{ gpss_patch_version }}-{{ gpss_os_version_gpdb }}-{{ gpss_arch_type }}.gppkg
  when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" ) and ( gpss_gpdb_version|regex_replace('[^0-9]','')|int >= 7 and gpss_os_version_gpdb|regex_replace('[^0-9]','')|int >= 8 )

#
- name: Verify if GPSS gppkg is installed
  become_user: gpadmin
  shell: ( source {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && {{ check_gpss_installed }} )
  args:
    executable: /bin/bash
  ignore_errors: true
  register: gpss_installed
  changed_when: False
  when: inventory_hostname in groups['master']

#
- debug: msg={{ gpss_installed.stdout }}
  when: inventory_hostname in groups['master']

#
- name: Stop if GPSS gppkg package is installed
  fail: msg="GPSS gppkg package is already installed!"
  when: ( inventory_hostname in groups['master'] and 'gpss' in gpss_installed.stdout )

#
- name: yum install daemonize
  become: yes
  yum:
    name: daemonize
    state: latest
  when: inventory_hostname in groups['master']

#
- name: Copy GPSS tarball file
  become_user: gpadmin
  copy: src=gpss-{{ gpss_gpdb_version }}-{{ gpss_major_version }}.{{ gpss_minor_version }}{{ gpss_patch_version }}-{{ gpss_os_version_kafka }}-x86_64.tar.gz dest={{ gpadmin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  when:  inventory_hostname in groups['master'] and gpss_install_tar

#
- name: Untar GPSS tarball archive
  become_user: gpadmin
  unarchive: src={{ gpadmin_home_dir }}/gpss-{{ gpss_gpdb_version }}-{{ gpss_major_version }}.{{ gpss_minor_version }}{{ gpss_patch_version }}-{{ gpss_os_version_kafka }}-x86_64.tar.gz dest={{ gpadmin_home_dir }} copy=no owner=gpadmin group=gpadmin
  when: inventory_hostname in groups['master'] and gpss_install_tar

#
- name: Install GPSS tarball in {{ gpdb_base_dir }}
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && cd {{ gpadmin_home_dir }}/gpss-{{ gpss_gpdb_version }}-{{ gpss_major_version }}.{{ gpss_minor_version }}{{ gpss_patch_version }}-{{ gpss_os_version_kafka }}-x86_64/ ; ./install_gpdb_component )
  async: 120
  poll: 5
  when: inventory_hostname in groups['master'] and gpss_install_tar

#
- name: Copy GPSS gppkg file
  become_user: gpadmin
  copy: src={{ gpss_package_name }} dest={{ gpadmin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  args:
    executable: /bin/bash
  when: ( inventory_hostname in groups['master'] and 'gpss' not in gpss_installed.stdout )

#
- name: Install GPSS gppkg package
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_install_cmd }} {{ gpadmin_home_dir }}/{{ gpss_package_name }} )
  ignore_errors: true
  when: inventory_hostname in groups['master']  # At GPDB Master

#
- name: Verify that database for GPSS extention is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ gpss_database_name }}'" )
  register: gpss_database_installed
  when: inventory_hostname in groups['master']

#
- name: Create database for GPSS
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && createdb {{ gpss_database_name }} )
  register: gpss_database_created
  when:
    - inventory_hostname in groups['master']
    - "'100' not in gpss_database_installed.stdout"

#
- name: Create extension for GPSS
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -d {{ gpss_database_name }} -tAc "CREATE extension gpss" )
  register: gpss_extension_installed
  when:
    - inventory_hostname in groups['master']
    - "'100' not in gpss_database_installed.stdout"

#
- name: Chown gpamdin for GPSS install directory
  become: yes
  file:
    dest: "{{ gpdb_base_dir }}/gpss"
    owner: gpadmin
    group: gpadmin
    mode: u=rwX,g=rX,o=rX
    state: directory
    recurse: yes
  when: inventory_hostname in groups['master']  # At Kafka Broker

#
- name: Creates working base directory for kafka and gpss
  file:
    path: "{{ item }}"
    state: directory
    owner: gpadmin
    group: gpadmin
    mode: 0775
  with_items:
    - "{{ gpss_base_dir }}"
    - "{{ gpss_log_dir }}"
  when: inventory_hostname in groups['master']

#
- name: Copy create table query file and gpss config file and json loadcfg yml file
  template: src=gpss/{{ item }}.j2 dest={{ gpss_base_dir }}/{{ item }} owner=gpadmin group=gpadmin mode=644 force=yes
  register: create_table_query_copied
  with_items:
    - "create_table.sql"
    - "gpss_config.json"
    - "jsonload_cfg.yaml"
  when: inventory_hostname in groups['master']

#
- name: Create table
  become: yes
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -d testdb -f {{ gpss_base_dir }}/create_table.sql )
  register: gpss_table_created
  when: inventory_hostname in groups['master']

#
- debug: msg={{ gpss_table_created }}
  when: inventory_hostname in groups['master'] and print_debug

#
- name: Start GPSS daemon
  become: yes
  become_user: gpadmin
  shell: ( source {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && daemonize $GPHOME/bin/gpss {{ gpss_base_dir }}/gpss_config.json --verbose --log-dir {{ gpss_log_dir }} )
  register: gpss_daemon_started
  when: inventory_hostname in groups['master']

#
- debug: msg={{ gpss_daemon_started }}
  when: inventory_hostname in groups['master'] and print_debug

#
- name: Sumit Job
  become: yes
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpsscli submit --verbose --name {{ gpss_job_name }} --gpss-port {{ gpss_port }} {{ gpss_base_dir }}/jsonload_cfg.yaml )
  register: gpss_job_submitted
  when: inventory_hostname in groups['master']

#
- debug: msg={{ gpss_job_submitted }}
  when: inventory_hostname in groups['master'] and print_debug

#
- name: List all jobs
  become: yes
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpsscli list --verbose --all --gpss-port {{ gpss_port }} )
  register: gpss_all_jobs_listed
  when: inventory_hostname in groups['master']

#
- debug: msg={{ gpss_all_jobs_listed }}
  when: inventory_hostname in groups['master'] and print_debug

#
- name: Start GPSS job
  become: yes
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpsscli start {{ gpss_job_name }} --verbose --gpss-port {{ gpss_port }} )
  register: gpss_job_started
  when: inventory_hostname in groups['master']

#
- debug: msg={{ gpss_job_started }}
  when: inventory_hostname in groups['master'] and print_debug

#
- name: Print new contents
  become: yes
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -d testdb -c "SELECT * FROM public.json_from_kafka;" )
  register: gpss_new_contents_printed
  when: inventory_hostname in groups['master']

#
- debug: msg={{ gpss_new_contents_printed }}
  when: inventory_hostname in groups['master'] and print_debug

#
- name: Print the status of GPSS job
  become: yes
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpsscli status {{ gpss_job_name }} --gpss-port {{ gpss_port }} )
  register: gpss_job_status_printed
  when: inventory_hostname in groups['master']

#
- debug: msg={{ gpss_job_status_printed }}
  when: inventory_hostname in groups['master'] and print_debug

#
#- name: Print the progress of GPSS job
#  become: yes
#  become_user: gpadmin
#  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpsscli progress {{ gpss_job_name }} --gpss-port {{ gpss_port }} )
#  register: gpss_job_progress_printed
#  when: inventory_hostname in groups['master']
#
#
#- debug: msg={{ gpss_job_progress_printed }}
#  when: inventory_hostname in groups['master'] and print_debug
