---
galaxy_info:
  author: vadikgo@gmail.com
  description: Minio installation/configuration role
  license: MIT
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
dependencies: []
