---
# greenplum-text-3.3.1-rhel7_x86_64.tar.gz
gptext_major_version: 3
gptext_minor_version: 5.0
gptext_patch_version:
gptext_build_version:
gptext_gpdb_version:
gptext_java_version: 1.8.0
gptext_rhel_name: rhel7
gptext_database_name: gptext_testdb
gptext_all_hosts: "mdw6 smdw6 sdw6-01 sdw6-02 sdw6-03"
# gptext_all_hosts: "mdw6 smdw6 sdw6-01 sdw6-02 sdw6-03"
# greenplum-text-2.2.1-rhel6_x86_64.tar.gz
# greenplum-text-3.4.3-rhel7_x86_64.tar.gz
