---
# greenplum-text-3.3.1-rhel7_x86_64.tar.gz
# greenplum-text-3.9.1-rhel8_x86_64.tar.gz

gptext:
  base_dir: '/usr/local'
  major_version: 3
  minor_version: 11.0
  patch_version: 
  build_version: 
  os_version: rhel8
  arch_type: x86_64
  bin_type: tar.gz
  gpdb_version: gpdb6
  java_version: 1.8.0
  os_name: rhel8
  database_name: gptext_testdb

