package_download_path : "/tmp"
gpdb:
  master_data_dir: /data/master/gpseg-1
  data_dir: /data
  base_dir: /usr/local
  admin_user: gpadmin
  admin_passwd: changeme
freeipa:
  admin_user: admin
  admin_passwd: changeme
  client_domain: jtest.pivotal.io
  client_server: lab.jtest.pivotal.io
  client_ipaddr: 192.168.0.101
  client_realm: JTEST.PIVOTAL.IO
  client_fqdn: "{{ hostvars[groups['master'][0]].ansible_hostname }}"
  client_extra_args: [ '--kinit-attempts=3', '--mkhomedir']
  ldap:
    database: ldap_testdb
    server: "192.168.0.101"
    cn: "cn=users,cn=accounts"
    dn: "dc=jtest,dc=pivotal,dc=io"
    users:
      - { username: jmoon, passwd: changeme, first_name: Jack, last_name: Moon }
      - { username: rmoon, passwd: changeme, first_name: Rose, last_name: Moon }
  kerberos:
    database: krb5_testdb
    client_principal: admin
    client_password: changeme
    client_keytab: /etc/krb5.keytab
    client_gpdb_keytab: /home/gpadmin/gpdb-kerberos.keytab
    client_keytab_fullpath: /etc/krb5.keytab
    users:
      - { username: gpuser,  passwd: changeme, first_name: GPadmin , last_name: Moon }
ssl:
  dir: "{{ gpdb.master_data_dir }}"
  days: 3660
  country: "KR"
  state: "Seoul"
  location: "Guro"
  organization: "Pivotal"
  common_name: "jtest.pivotal.io"
  email: "jomoon@pivotal.io"
