---
- name: Verify if PostGIS GPPKG is Installed
  become_user: gpadmin
  shell: ( source {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ check_postgis_installed }} )
  register: postgis_installed
  ignore_errors: true
  changed_when: False
  when: inventory_hostname in groups['master']


- name: Print the Result if PostGIS Extensions are Not Installed
  debug:
    msg: "{{ postgis_installed.stdout }}"
  ignore_errors: true
  when: inventory_hostname in groups['master']


- name: Stop if PostGIS GPPKG Package is Not Installed
  fail: msg="PostGIS gppkg package is not installed!"
  ignore_errors: true
  when: ( inventory_hostname in groups['master'] and 'postgis' not in postgis_installed.stdout )


- name: Uninstall the PostGIS GPPKG Pakcage
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_remove_cmd }} {{ postgis_package_name }} )
  register: postgis_package_uninstalled
  ignore_errors: true
  until: postgis_package_uninstalled is succeeded
  retries: 10
  delay: 30
  changed_when: postgis_database_installed == True
  when: inventory_hostname in groups['master']


- name: Check if the Directory of PostGIS Package is Still Remained
  stat: path={{ gpdb.base_dir }}/greenplum-db/postgis
  register: postgis_dir_remained
  ignore_errors: true
  when: inventory_hostname in groups['master']


#- name: Remove PostGIS Directory still remained
#  file:
#    owner: gpadmin
#    group: gpadmin
#    path: "{{ gpdb.base_dir }}/greenplum-db/postgis"
#    state: absent
#  when:
#    - inventory_hostname in groups['master']
#    - postgis_dir_remained.stat.exists == True

