---

# for now fail if it's not a Red Hat based system
- name: Check OS (PGCC v2)
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'

- name: Installation for Red Hat / CentOS
  include: postgis-install.yml
  tags: install

- name: Installation for Red Hat / CentOS
  include: postgis-uninstall.yml
  tags: uninstall
