---
# For Now Fail If It's Not Suppoted OS
- name: Check OS ( GPDB )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Setup Hostname and IP Address in /etc/hosts
  import_tasks: init-hosts.yml
  tags: install


- name: Install Prerequiestes Software Packages and Setup Hostname, IP Addresses as well as
  import_tasks: install.yml
  tags: install


- name: Create SSH Key and Exchange it for sudo user among All Hosts
  import_tasks: ssh_sudo_user.yml
  tags: install


- name: Create SSH Key and Exchange it for root user among All Hosts
  import_tasks: ssh_root_user.yml
  tags: install


- name: Uninstall SSH Keys and sudo users as well as Prerequiestes Software Packages
  import_tasks: uninstall.yml
  tags: uninstall

