---
#
- name: Create .bash_history if not exist
  become_user: "{{ sudo_user }}"
  copy:
    dest: ~/.bash_history
    content: ""
    force: no

#
- name: Add sudo line to bash history
  become_user: "{{ sudo_user }}"
  lineinfile:
    dest: ~/.bash_history
    line: "sudo /bin/bash --login"
    state: present

#
- name: Check .ssh local directory exists
  become_user: "{{ sudo_user }}"
  stat:
    path: ~/.ssh
  register: ssh_user_directory_exists_check

#
- name: Create ~/.ssh directory in "{{ sudo_user }}" user home directory
  become_user: "{{ sudo_user }}"
  file:
    path: "~/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ sudo_user }}"
    group: "{{ sudo_group }}"
  register: ssh_user_directory_creation
  when: ssh_user_directory_exists_check is defined and ssh_user_directory_exists_check.stat.exists == false

#
- name: Check .ssh key file exists
  become_user: "{{ sudo_user }}"
  stat:
    path: "~/.ssh/{{ item }}"
  register: ssh_user_key_file_exists_check
  with_items:
    - "{{ ssh_key_filename }}"
    - "{{ ssh_key_filename }}.pub"

#
- name: Adding the fingerprint
  become_user: "{{ sudo_user }}"
  shell: "ssh-keyscan -t rsa {{ item }} >> ~/.ssh/known_hosts"
  register: ssh_user_fingerprint_add
  with_items:
    - "{{ groups['all'] }}"

#
- name: Generate ssh key of "{{ sudo_user }}" user on local machine
  become_user: "{{ sudo_user }}"
  shell: "/usr/bin/ssh-keygen -t rsa -f ~/.ssh/{{ssh_key_filename}} -P ''"
  register: ssh_user_key_creation
  when:
    - ssh_user_key_file_exists_check is defined and ssh_user_key_file_exists_check.results[0].stat.exists == false and ssh_user_key_file_exists_check.results[1].stat.exists == false
  failed_when: ssh_user_key_creation.rc != 0

#
- name: Distribute the ssh key of "{{ sudo_user }}" user to the remote hosts
  become_user: "{{ sudo_user }}"
  shell: "sshpass -p \"{{sudo_user_pass}}\" ssh-copy-id -i ~/.ssh/{{ ssh_key_filename }}.pub \"{{ sudo_user }}@{{ item }}\""
  register: ssh_copy_user_id_execution
  with_items:
    - "{{ groups['all'] }}"
  failed_when:
    - ssh_copy_user_id_execution.rc != 0

#
- name: Add user to "{{ wheel_group }}" group
  shell: usermod -aG "{{ wheel_group }}" "{{ sudo_user }}"
  args:
    executable: /bin/bash
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

#
- name: Add user to "{{ wheel_group }}" group
  shell: usermod -aG "sudo" "{{ sudo_user }}"
  args:
    executable: /bin/bash
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#
- name: Check ssh to remote hosts works
  become_user: "{{ sudo_user }}"
  shell: "hostname; id"
  register: ssh_connection_test
  failed_when: ssh_connection_test.rc != 0

#
- name: Print the connectivity test results
  become_user: "{{ sudo_user }}"
  debug:
    var: ssh_connection_test.stdout_lines

#
- name: Copy Sudo User SSH Key from Local to All Hosts
  become_user: "{{ local_sudo_user }}"
  shell: |
    sshpass -p "changeme" ssh-copy-id -f -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pub {{ sudo_user }}@{{ hostvars[item][_netdev]['ipv4']['address'] }}
  register: ssh_copy_id_keys
  with_items: "{{ groups['all'] }}"
  delegate_to: localhost
  failed_when: ssh_copy_id_keys.rc != 0
  when: inventory_hostname in hostvars[groups['all'][0]].ansible_hostname

