---

# Install PLContainer extention on Greenplum database

- name: Check if the GPDB software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed

- name: Stop if GPDB software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when: gpdb_installed.stat.exists != True

- name: Verify that database is up and running
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -c "SELECT VERSION()" )
  register: select_version
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

- name: Verify if plcontainer gppkg is installed
  become_user: gpadmin
  command: 'rpm -q plcontainer --dbpath /usr/local/greenplum-db/share/packages/database'
  ignore_errors: true
  register: plcontainer_installed
  changed_when: False
  when: inventory_hostname in groups['master']

- name: Stop if plcontainer gppkg package is not installed
  fail: msg="plcontainer gppkg package is not installed!"
  when:
    - inventory_hostname in groups['master']
    - "'package plcontainer is not installed' not in plcontainer_installed.stdout"

- name: Copy plcontainer gppkg file
  copy: src=plcontainer-{{ plcontainer_prefix_major_version }}{{ plcontainer_major_version }}.{{ plcontainer_minor_version }}.{{ plcontainer_patch_version }}-{{ plcontainer_gpdb_version }}-{{ plcontainer_rhel_version }}_x86_64.gppkg dest={{ gpadmin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  when:
    - inventory_hostname in groups['master']
    - "'package plcontainer is not installed' in plcontainer_installed.stdout"

- name: Install plcontainer package
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gppkg -i {{ gpadmin_home_dir }}/plcontainer-{{ plcontainer_prefix_major_version }}{{ plcontainer_major_version }}.{{ plcontainer_minor_version }}.{{ plcontainer_patch_version }}-{{ plcontainer_gpdb_version }}-{{ plcontainer_rhel_version }}_x86_64.gppkg )
  when:
    - inventory_hostname in groups['master']
    - "'package plcontainer is not installed' in plcontainer_installed.stdout"

- name: Restart GPDB and apply parameters for plcontainer in greenplum_path.sh
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  async: 60
  poll: 5
  when:
    - inventory_hostname in groups['master']

- name: Verify that database for plcontainer is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ plcontainer_database_name }}'" )
  register: plcontainer_database_installed
  when: inventory_hostname in groups['master']

- name: Create database for plcontainer
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && createdb {{ plcontainer_database_name }} )
  register: plcontainer_database_created
  when: "'100' not in plcontainer_database_installed.stdout"

- name: Enable PL/Container for a databases by running
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -d {{ plcontainer_database_name }} -f {{ gpdb_base_dir }}/greenplum-db/share/postgresql/plcontainer/plcontainer_install.sql )
  register: plcontainer_database_enabled
  when: "'100' not in plcontainer_database_installed.stdout"

- name: Initialize PLContainer configuration on the GPDB hosts
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && plcontainer configure --reset )
  register: plcontainer_configuration_initialized
  when: inventory_hostname in groups['master']
