---
- name: Check OS ( PL/Container )
  fail: msg="Not a Red Hat based system!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Install PL/Container
  import_tasks: install.yml
  tags: install


- name: Uninstall PL/Container
  import_tasks: uninstall.yml
  tags: uninstall

