---
- name: Verify if PL/Java Pakcage is Installed
  become_user: gpadmin
  shell: ( source {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ check_pljava_installed }} )
  args:
    executable: /bin/bash
  ignore_errors: true
  register: pljava_installed
  changed_when: False
  when: inventory_hostname in groups['master']


- name: Stop if PL/Java Gppkg Package is Already Installed
  fail: msg="PL/Java gppkg package is already installed!"
  when: ( inventory_hostname in groups['master'] and 'pljava' in pljava_installed.stdout )


- name: Copy PL/Java Gppkg Package File
  copy: src={{ pljava_package_name }} dest={{ gpdb.admin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  when: ( inventory_hostname in groups['master'] and 'pljava' not in pljava_installed.stdout )


- name: Install PL/Java GPPkg Package
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_install_cmd }} {{ gpdb.admin_home_dir }}/{{ pljava_package_name }} )
  args:
    executable: /bin/bash
  when: ( inventory_hostname in groups['master'] and 'pljava' not in pljava_installed.stdout )
