---
# for now fail if it's not a Red Hat based system
- name: Check OS (PGCC v2)
  fail: msg="Not a Red Hat based system!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Install PL/Java for {{ ansible_distribution }}
  import_tasks: install.yml
  tags: install

#
- name: Uninstall PL/Java for {{ ansible_distribution }}
  import_tasks: uninstall.yml
  tags: uninstall

