---
# Uninstall PL/Java extention on GPDB

#
- set_fact:
    gppkg_remove_cmd: "gppkg -r"
    pljava_package_name: pljava-{{ pljava.prefix_major_version }}{{ pljava.major_version }}.{{ pljava.minor_version }}.{{ pljava.patch_version }}-gp{{ pljava.gpdb_version }}-{{ pljava.os_version }}_{{ pljava.arch_type }}
  when: inventory_hostname in groups['master'] and pljava.gpdb_version|int <= 6

#
- set_fact:
    gppkg_remove_cmd: "gppkg -a remove"
    pljava_package_name: pljava
  when: inventory_hostname in groups['master'] and pljava.gpdb_version|int == 7

#
- name: Check if the GPDB software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed

#
- name: Stop if GPDB software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when: gpdb_installed.stat.exists != True

#
- name: Verify that database for PL/Java is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ pljava.database_name }}'" )
  register: pljava_database_installed
  when: inventory_hostname in groups['master']

#
- name: Remove PL/Java Support far a Database of GPDB 4.x
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && droplang pljava -d {{ pljava.database_name }}; )
  register: pljava_support_removed
  when: ( inventory_hostname in groups['master'] and pljava.gpdb_version == "4.3" and '100' in pljava_database_installed.stdout )

#
- name: Remove PL/Java Support far a Database of GPDB 5x / 6.x
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -d {{ pljava.database_name }} -c 'DROP EXTENSION pljava;' )
  register: pljava_support_removed
  ignore_errors: yes
  when: ( inventory_hostname in groups['master'] and pljava.gpdb_version|int == 6 and '100' in pljava_database_installed.stdout )

#
- name: Drop database for PL/Java
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && dropdb {{ pljava.database_name }} )
  register: pljava_database_deleted
  when: ( inventory_hostname in groups['master'] and '100' in pljava_database_installed.stdout )

#
- name: Uninstall the PL/Java language extension
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_remove_cmd }} {{ pljava_package_name }} )
  register: pljava_extension_uninstalled
  ignore_errors: true
  when: inventory_hostname in groups['master']

#
- name: Restart the Greenplum Database
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  async: 60
  poll: 5
  when: inventory_hostname in groups['master']
