---
- name: Start PGBouncer
  become: yes
  service:
    name: pgbouncer
    state: started


- name: Stop PGBouncer
  become: yes
  service:
    name: pgbouncer
    state: stopped


- name: Restart PGBouncer
  become: yes
  service:
    name: pgbouncer
    state: restarted


- name: Reload PGBouncer
  become: yes
  service:
    name: pgbouncer
    state: reloaded


- name: Restart MonIT
  become: yes
  service:
    name: monit
    state: restarted


- name: Restart Collectd
  become: yes
  service:
    name: collectd
    state: restarted

