---
- name: Check if the MADLib Extention is Already Installed
  stat: path={{ gpdb.base_dir }}/greenplum-db/madlib
  register: madlib_installed
  when: inventory_hostname in groups['master']


- name: Stop if MADLib Extention Software is Already Installed
  fail: msg="MADLib Extention Software is Already Installed!"
  when: inventory_hostname in groups['master'] and madlib_installed.stat.exists == True


- name: Copy MADLib Extention tar.gz File
  copy: src={{ madlib_package_name }}.tar.gz dest={{ gpdb.admin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  when: inventory_hostname in groups['master'] and madlib_installed.stat.exists != True


- name: Untar MADLib Extention Archive
  unarchive: src={{ gpdb.admin_home_dir }}/{{ madlib_package_name }}.tar.gz dest={{ gpdb.admin_home_dir }} copy=no owner=gpadmin group=gpadmin
  when: inventory_hostname in groups['master'] and madlib_installed.stat.exists != True


- name: Install MADLib Extention Package
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_install_cmd }} {{ gpdb.admin_home_dir }}/{{ madlib_directory_name }}/{{ madlib_package_bin_name }} )
  args:
    executable: /bin/bash
  register: madlib_package_installed
  ignore_errors: true
  async: 600
  poll: 10
  # until: madlib_package_installed is succeeded
  # retries: 10
  # delay: 30
  when: inventory_hostname in groups['master'] and madlib_installed.stat.exists != True

