---

# Install madlib extention on Greenplum database

- name: Check if the Greenplum Database software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed
  when: inventory_hostname in groups['master']

- name: Stop if database software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when: inventory_hostname in groups['master'] and  gpdb_installed.stat.exists != True

- name: Verify that database is up and running
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -c 'SELECT VERSION()' )
  args:
    executable: /bin/bash
  register: select_version
  failed_when: "'(Greenplum Database ' not in select_version.stdout"
  when: inventory_hostname in groups['master']

- name: Check if the madlib extention is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db/madlib
  register: madlib_installed
  when: inventory_hostname in groups['master']

- name: Stop if madlib extention software is already installed
  fail: msg="madlib extention software is already installed!"
  when: inventory_hostname in groups['master'] and  madlib_installed.stat.exists == True

#
- set_fact:
    madlib_package_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}+{{ madlib_build_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}
    madlib_package_bin_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}+{{ madlib_build_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}.gppkg
    madlib_directory_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}+{{ madlib_build_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}
    gppkg_install_cmd: "gppkg -i"
  when:
    - inventory_hostname in groups['master']
    - ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and madlib_major_version <= 1

#
- set_fact:
    madlib_package_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}
    madlib_package_bin_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}.gppkg.tar.gz
    madlib_directory_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}
    gppkg_install_cmd: "gppkg -a install"
  when:
    - inventory_hostname in groups['master']
    - ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and madlib_major_version >= 2

#
- set_fact:
    madlib_package_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}+{{ madlib_build_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}
    madlib_package_bin_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}+{{ madlib_build_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}.gppkg
    madlib_directory_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}+{{ madlib_build_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}
    gppkg_install_cmd: "gppkg -i"
  when:
    - inventory_hostname in groups['master']
    - ( ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" ) and madlib_major_version <= 1

#
- set_fact:
    madlib_package_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}+{{ madlib_build_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}
    madlib_package_bin_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}.gppkg.tar.gz
    madlib_directory_name: madlib-{{ madlib_major_version }}.{{ madlib_minor_version }}.{{ madlib_patch_version }}-{{ madlib_gpdb_version }}-{{ madlib_os_version }}-{{ madlib_arch_type }}
    gppkg_install_cmd: "gppkg -a install"
  when:
    - inventory_hostname in groups['master']
    - ( ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" ) and madlib_major_version >= 2


#
- name: Copy madlib extention tar.gz file
  copy: src={{ madlib_package_name }}.tar.gz dest={{ gpadmin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  when: inventory_hostname in groups['master'] and madlib_installed.stat.exists != True

#
- name: Untar madlib extention archive
  unarchive: src={{ gpadmin_home_dir }}/{{ madlib_package_name }}.tar.gz dest={{ gpadmin_home_dir }} copy=no owner=gpadmin group=gpadmin
  when: inventory_hostname in groups['master'] and madlib_installed.stat.exists != True

#
- name: Install madlib extention package
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_install_cmd }} {{ gpadmin_home_dir }}/{{ madlib_directory_name }}/{{ madlib_package_bin_name }} )
  args:
    executable: /bin/bash
  register: madlib_package_installed
  async: 600
  poll: 10
  # until: madlib_package_installed is succeeded
  # retries: 10
  # delay: 30
  when: inventory_hostname in groups['master'] and madlib_installed.stat.exists != True

#
- name: Verify that database for MADlib Extention is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ madlib_database_name }}'" )
  args:
    executable: /bin/bash
  register: madlib_database_installed
  when: inventory_hostname in groups['master']

#
- name: Create database for madlib
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && createdb {{ madlib_database_name }} )
  args:
    executable: /bin/bash
  register: madlib_database_created
  when: inventory_hostname in groups['master'] and "'100' not in madlib_database_installed.stdout"

- name: Add madlib function
  become_user: root
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && $GPHOME/madlib/bin/madpack -s madlib -p greenplum -c gpadmin@{{ madlib_mdw_hostname }}:5432/{{ madlib_database_name }} install )
  args:
    executable: /bin/bash
  register: madlib_function_installed
  changed_when: madlib_database_created == True
  when: inventory_hostname in groups['master']

- name: Check if madlib function are added
  become_user: root
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && $GPHOME/madlib/bin/madpack -s madlib -p greenplum -c gpadmin@{{ madlib_mdw_hostname }}:5432/{{ madlib_database_name }} install-check )
  args:
    executable: /bin/bash
  changed_when: madlib_function_installed == True
  when: inventory_hostname in groups['master']
