---
#
- name: Install RPM Packages for PGBouncer Info
  package:
    name: "{{ item }}"
    state: "{{ _pgbouncer.package_state }}"
  with_items: "{{ _pgbouncer.packages }}"

#
- name: Install Collectd and Monit package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python2
    - python2-psycopg2
    - monit
    - collectd
    - collectd-python
    - collectd-web

#
- name: Install Python Collectd Modules for PGBouncer Monitoring
  become: true
  become_user: root
  shell: ( pip2 install {{ item }} )
  async: 60
  poll: 5
  register: pip3_python_collectd_modules_for_pgbouncer
  with_items:
    - "collectd"

#
- name: Alternative Python Version to Python2 for installing collectd and jevent RPM packages
  become: true
  become_user: root
  command: alternatives --set python /usr/bin/python2
  ignore_errors: yes
  register: python_version_alternative
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8

