---

- import_tasks: install.yml
  tags: install
  # tags: [pgbouncer, pgbouncer-install]

- import_tasks: configure.yml
  tags: install
  # tags: [pgbouncer, pgbouncer-configure]

- import_tasks: monit.yml
  when: monit_protection is defined and monit_protection == true
  tags: install
  # tags: [pgbouncer, pgbouncer-monit]

- import_tasks: collectd.yml
  when: collectd_monitoring is defined and collectd_monitoring == true
  tags: install
  # tags: [pgbouncer, pgbouncer-collectd]

- import_tasks: uninstall.yml
  tags: uninstall
  # tags: [pgbouncer, pgbouncer-install]

