---
- name: Ensure monit is running
  become: yes
  service:
    name: monit
    state: started


# template a config file
- name: (Monit) copy the pgbouncer monit service file
  become: yes
  become_user: root
  template:
    src: etc_monit_conf.d_pgbouncer.j2
    dest: /etc/monit.d/pgbouncer
  notify: Restart MonIT


# we need to restart before monit is called
- meta: flush_handlers


# Manage the state of program "pgbouncer" to be in "started" state.
- name:  Manage the state of program "pgbouncer" to be in "started" state.
  become: yes
  become_user: root
  monit:
    name: pgbouncer
    state: started
  ignore_errors: true

