#
- name: Stop services for Monit, Collectd, PGBouncer
  become: yes
  systemd:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items:
    - monit
    - collectd
    - pgbouncer

#
- name: Delete all configuraion files for Monit, Collectd, PGBouncer
  become: true
  become_user: root
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/collectd/python"
    - "/etc/collectd.d/pgbouncer_gpdb_info.conf"
    - "/data/master/gpseg-1/pgbouncer"
    - "/usr/local/greenplum-db/etc/pgbouncer"
    - "/etc/monit.d/pgbouncer"
    - "/etc/systemd/system/pgbouncer.service"

#
- name: Reload systemd daemon after deleting PGBouncer service
  become: true
  systemd:
    daemon_reload: yes

#
- name: Uninstall RPM Packages for PGBouncer Info
  become: true
  package:
    name: "{{ item }}"
    state: "{{ _pgbouncer.package_state }}"
  with_items: "{{ _pgbouncer.packages }}"

#
- name: Uninstall Python collectd modules for PGBouncer monitoring
  become: true
  become_user: root
  shell: ( pip2 uninstall {{ item }} -y )
  async: 60
  poll: 5
  ignore_errors: yes
  register: pip3_python_collectd_modules_for_pgbouncer
  with_items:
    - "collectd"

#
- name: Uninstall Collectd and Monit Package
  become: true
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - monit
    - collectd-web
    - collectd-python
    - collectd
    - python2-psycopg2
    - python2

#
- name: Alternative Python version to python3 for returning back
  become: true
  become_user: root
  command: alternatives --set python /usr/bin/python3
  ignore_errors: yes
  register: python_version_alternative
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int <= 8

