---
#
- name: Verify that Greenplum Database is up and running
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -c "SELECT VERSION()" )
  args:
    executable: /bin/bash
  register: select_version
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

#
- name: Add ldap configuration file to authenticate ldap user into Greenplum Database
  become_user: gpadmin
  lineinfile:
    dest: "{{ master_data_dir }}/{{ item.file }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { file: "pg_hba.conf",     line: "host  {{ gpdb_ldap_database }}  all  192.168.0.0/24  ldap  ldapurl=ldap://{{ gpdb_ldap_server }} ldapprefix=\"uid=\" ldapsuffix=\",{{ gpdb_ldap_cn }},{{ gpdb_ldap_dn }}\"",           state: present }
  register: gpdb_ldap_config
  when: inventory_hostname in groups['master']

#
- name: Create role for LDAP Users
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && createuser {{ item.username }} )
  args:
    executable: /bin/bash
  register: ldap_users_added
  with_items: "{{ gpdb_ldap_users }}"
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

#
- name: Create database for LDAP Users
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && createdb testdb )
  args:
    executable: /bin/bash
  register: ldap_database_created
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"
