---
- name: Check if Any Version of Greenplum MPP Database is Already Installed
  stat: path={{ gpdb.base_dir }}/{{ link_path }}
  register: check_gpdb_link


- name: Check if the Greenplum MPP Database Version is Already Installed
  stat: path={{ gpdb.base_dir }}/{{ install_path }}
  register: check_gpdb_dir


- name: Sanity Check for {{ gpdb.base_dir }}/{{ gpdb.pkg_name }}
  fail: msg="{{ gpdb.base_dir }}/cloudberry-db or {{ gpdb.base_dir }}/{{ install_path }} Already Exists!"
  when: check_gpdb_link.stat.exists == True or check_gpdb_link.stat.exists == True


- name: Set Default Values for Run Mode Variables
  set_fact:
    gpdb_install: False
    gpdb_linkchange: False


- name: Identify Greenplum MPP Database Installation
  set_fact:
    gpdb_install: True
  when: check_gpdb_dir.stat.exists != True and check_gpdb_link.stat.exists != True


# If the link points to a different existing directory, it's a link change
- name: Identify Greenplum MPP Database Linkchange
  set_fact:
    gpdb_linkchange: True
  when: check_gpdb_link.stat.exists != True


- name: Greenplum MPP Database Installation
  debug: msg="New Greenplum MPP Database installation"
  when: gpdb_install == True


- name: Greenplum MPP Database Link Change
  debug: msg="Changing link to Greenplum MPP Database version"
  when: gpdb_linkchange == True


- name: Greenplum MPP Database - Nothing to do
  debug: msg="Nothing to do (no installation/upgrade required)"
  when: gpdb_install == False and gpdb_linkchange == False


- debug: msg={{ gpdb_install }}
- debug: msg={{ gpdb_linkchange }}
- debug: msg={{ gpdb_install }}
- debug: msg={{ install_path }}
- debug: msg={{ link_path }}

