---
- name: Add the Path of Greenplum Database Variable file into .bashrc
  become_user: gpadmin
  lineinfile:
    dest: /home/gpadmin/.bashrc
    line: "source /usr/local/greenplum-db/greenplum_path.sh"
    state: present


- name: Verify that Greenplum Database is Up and Running
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -c "SELECT VERSION()" )
  args:
    executable: /bin/bash
  register: select_version
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"


- name: Change gpadmin password to Check Remote Login via SSL
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -c "alter user gpadmin with password 'changeme'" )
  args:
    executable: /bin/bash
  register: gpadmin_password_changed
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"


- name: Greenplum Database Installation
  debug: msg="Greenplum Database {{ install_path }} installed"
  when: gpdb_install == True


- name: Greenplum Database Version switched
  debug: msg="Greenplum Database {{ install_path }} is active"
  when: gpdb_linkchange == True

