---
# Install Greenplum Database on RedHat / CentOS / Rocky / Ubuntu / Debian

# for now fail if it's not suppoted OS
- name: Check OS ( GPDB )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
# - name: Install Greenplum Database
#  import_tasks: install.yml

- name: xx
  import_tasks: 00-check-gpdb-installed.yml
  tags: install

- name: xx
  import_tasks: 01-set-gpdb-facts.yml
  tags: install

- name: xx
  import_tasks: 02-prepare-os-parameters.yml
  tags: install

- name: xx
  import_tasks: 03-install-gpdb.yml
  tags: install

- name: xx
  import_tasks: 04-initialize-gpdb.yml
  tags: install

- name: xx
  import_tasks: 05-config-resource-group.yml
  tags: install

- name: xx
  import_tasks: 06-enable-ssl.yml
  tags: install

- name: xx
  import_tasks: 07-finalize-gpdb.yml
  tags: install

#
- name: Uninstall Greenplum Database
  import_tasks: uninstall.yml
  tags: uninstall
