---
- name: Check OS ( GPDB )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Greenplum MPP Database
  import_tasks: set-gpdb-facts.yml
  tags: install, uninstall, prepare


- name: Check if Greenplum MPP Database is Installed Already
  import_tasks: check-gpdb-installed.yml
  tags: prepare, install, deploy, init, enable


- name: Prepare OS Parameters
  import_tasks: prepare-os-parameters.yml
  tags: prepare
  when: ( env is defined and env == true ) or ( gpdb_all is defined and gpdb_all == true )


- name: Install Greenplum MPP Database Software Binary
  import_tasks: install-gpdb.yml
  tags: install, deploy, init
  when: ( db is defined and db == true ) or ( gpdb_all is defined and gpdb_all == true )


- name: Initialize Greenplum MPP Database
  import_tasks: init-gpdb.yml
  tags: install, init, deploy
  when: ( db is defined and db == true ) or ( gpdb_all is defined and gpdb_all == true )


- name: Finalize Greenplum MPP Database
  import_tasks: finalize-gpdb.yml
  tags: install, deploy
  when: ( db is defined and db == true ) or ( gpdb_all is defined and gpdb_all == true )


- name: Enable Resource Group
  import_tasks: rg/enable-resource-group.yml
  tags: enable
  when: ( rg is defined and rg == true ) or ( gpdb_all is defined and gpdb_all == true )


- name: Enable SSL
  import_tasks: ssl/enable-ssl.yml
  tags: enable
  when: ( ssl is defined and ssl == true ) or ( gpdb_all is defined and gpdb_all == true )


- name: Enable LDAP Authentication
  import_tasks: ldap/enable-ldap.yml
  tags: enable, install
  when: ( ldap is defined and ldap == true )


- name: Enable Kerberos Authentication
  import_tasks: krb5/enable-kerberos.yml
  tags: enable, install
  when: ( krb5 is defined and krb5 == true )


- name: Uninstall LDAP Authentication
  import_tasks: ldap/uninstall-ldap.yml
  tags: disable, uninstall
  when: ( ldap is defined and ldap == true )


- name: Uninstall Kerberos Authentication
  import_tasks: krb5/uninstall-kerberos.yml
  tags: disable, uninstall
  when: ( krb5 is defined and krb5 == true )


- name: Disable Resource Group
  import_tasks: rg/disable-resource-group.yml
  tags: disable, uninstall
  when: ( rg is defined and rg == true ) or ( gpdb_all is defined and gpdb_all == true )


- name: Uninstall Greenplum MPP Database
  import_tasks: uninstall.yml
  tags: uninstall, destroy
  when: ( db is defined and db == true ) or ( gpdb_all is defined and gpdb_all == true )


- name: Upgrade Greenplum MPP Database
  import_tasks: upgrade.yml
  tags: upgrade
  when: ( db is defined and db == true ) or ( gpdb_all is defined and gpdb_all == true )


