---
# Install Greenplum Database on RedHat / CentOS / Rocky / Ubuntu / Debian
#
# For Now Fail if It's Not Suppoted OS
- name: Check OS ( GPDB )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Check if Greenplum Database is Installed Already
  import_tasks: check-gpdb-installed.yml
  tags:
    - install
    - uninstall
  when: check_install_gpdb == true


- name: Set Facts for Greenplum Database
  import_tasks: set-gpdb-facts.yml
  tags:
    - install
    - uninstall
  when: set_gpdb_facts == true


- name: Prepare OS Parameters
  import_tasks: prepare-os-parameters.yml
  tags: install
  when: prepare_os_parameters == true


- name: Install Greenplum Database Software Binary
  import_tasks: install-gpdb.yml
  tags: install
  when: install_gpdb == true


- name: Initialize Greenplum Database
  import_tasks: initialize-gpdb.yml
  tags: install
  when: initialize_gpdb == true


- name: Enable LDAP Authentication
  import_tasks: enable-ldap.yml
  tags: install
  when: enable_ldap == true


- name: Enable Resource Group
  import_tasks: enable-resource-group.yml
  tags: install
  when: config_rg == true


- name: Enable SSL
  import_tasks: enable-ssl.yml
  tags: install
  when: enable_ssl == true


- name: Enable Kerberos Authentication
  import_tasks: enable-kerberos.yml
  tags: install
  when: enable_kerberos == true


- name: Finalize Greenplum Database
  import_tasks: finalize-gpdb.yml
  tags: install
  when: finalize_gpdb == true


- name: Uninstall LDAP Authentication
  import_tasks: uninstall-ldap.yml
  tags: uninstall
  when: enable_ldap == true


- name: Uninstall Kerberos Authentication
  import_tasks: uninstall-kerberos.yml
  tags: uninstall
  when: enable_kerberos == true


- name: Disable Resource Group
  import_tasks: disable-resource-group.yml
  tags: uninstall
  when: config_rg == true


- name: Uninstall Greenplum Database
  import_tasks: uninstall.yml
  tags: uninstall


- name: Upgrade Greenplum Database
  import_tasks: upgrade.yml
  tags: upgrade

