---
# Install Greenplum Database on RedHat / CentOS / Rocky / Ubuntu / Debian

# for now fail if it's not suppoted OS
- name: Check OS ( GPDB )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Installation of gpdb for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: install.yml
  tags: install

#
- name: Uninstallation of gpdb for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: uninstall.yml
  tags: uninstall

