---
# Install Greenplum Database on RedHat / CentOS / Rocky / Ubuntu / Debian
#
# For now fail if it's not suppoted OS
- name: Check OS ( GPDB )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

# - name: Install Greenplum Database
#  import_tasks: install.yml

#
- name: Check if Greenplum is installed already
  import_tasks: check-gpdb-installed.yml
  tags: install
  when: check_install_gpdb == true

#
- name: Set facts for Greenplum
  import_tasks: set-gpdb-facts.yml
  tags: install
  when: set_gpdb_facts == true

#
- name: Prepare OS parameters
  import_tasks: prepare-os-parameters.yml
  tags: install
  when: prepare_os_parameters == true

#
- name: Install Greenplum
  import_tasks: install-gpdb.yml
  tags: install
  when: install_gpdb == true

#
- name: Initialize Greenplum
  import_tasks: initialize-gpdb.yml
  tags: install
  when: initialize_gpdb == true

#
- name: Enable LDAP Authentication
  import_tasks: enable-ldap.yml
  tags: install
  when: enable_ldap == true

#
- name: Configure Resource Group
  import_tasks: config-resource-group.yml
  tags: install
  when: config_rg == true

#
- name: Enable SSL
  import_tasks: enable-ssl.yml
  tags: install
  when: enable_ssl == true

#
- name: Enable Kerberos Authentication
  import_tasks: enable-kerberos.yml
  tags: install
  when: enable_kerberos == true

#
- name: Finalize Greenplum
  import_tasks: finalize-gpdb.yml
  tags: install
  when: finalize_gpdb == true

#
- name: Uninstall LDAP Authentication
  import_tasks: uninstall-ldap.yml
  tags: uninstall
  when: enable_ldap == true

#
- name: Uninstall Kerberos Authentication
  import_tasks: uninstall-kerberos.yml
  tags: uninstall
  when: enable_kerberos == true

#
- name: Uninstall Greenplum Database
  import_tasks: uninstall.yml
  tags: uninstall
