---
#
- name: Verify that Greenplum Database is up and running
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -c "SELECT VERSION()" )
  args:
    executable: /bin/bash
  register: select_version
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

#
- name: Drop database for LDAP Users
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && dropdb "{{ freeipa.ldap.database }}" )
  args:
    executable: /bin/bash
  register: ldap_database_dropped
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

#
- name: Delete a service for
  become: true
  shell: |
    echo {{ freeipa.admin_passwd }} | kinit {{ freeipa.admin_user }}
    ipa service-del postgres/{{ freeipa.client_fqdn }}.{{ freeipa.client_domain }}@{{ freeipa.client_realm }}
    ipa host-del {{ freeipa.client_fqdn }}.{{ freeipa.client_domain }}
  args:
    executable: /bin/bash
  register: gpdb_service_deleted
  ignore_errors: true
  when: inventory_hostname in groups['master']

#
- name: Drop role for LDAP Users
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -c "DROP USER {{ item.username }}" )
  args:
    executable: /bin/bash
  register: ldap_users_dropped
  ignore_errors: true
  with_items: "{{ freeipa.ldap.users }}"
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

#
- name: Delte User in FreeIPA Server
  become: yes
  shell: |
    echo {{ freeipa.admin_passwd }} | kinit {{ freeipa.admin_user }}
    echo {{ item.passwd }} | ipa user-del {{ item.username }}
  args:
    executable: /bin/bash
  register: ipa_user_deleted
  ignore_errors: true
  with_items: "{{ freeipa.ldap.users }}"
  when: inventory_hostname in groups['master']

#
- name: Uninstall FreeIPA Client
  become: yes
  shell: ipa-client-install --uninstall -U
  args:
    executable: /bin/bash
  register: ipa_client_uninstalled
  when: inventory_hostname in groups['master']

# State is set to Absent to remove if the Searching Line is found
- name: Remove LDAP configuration file to authenticate LDAP user into Greenplum Database
  become_user: gpadmin
  lineinfile:
    path: "{{ gpdb.master_data_dir }}/{{ item.file }}"
    regexp: "{{ item.regexp }}"
    state: "{{ item.state }}"
  with_items:
    - { file: "pg_hba.conf", regexp: "ldap", state: absent }
  register: gpdb_ldap_pg_hba_config_removed
  when: inventory_hostname in groups['master']

#
- name: Uninstall FreeIPA Client Package
  become: true
  package:
    name: ipa-client
    state: absent
  async: 360
  poll: 5
  register: ipa_client_pkgs_uninstalled
  when: inventory_hostname in groups['master']

#
- name: Remove hostname and ip address entries in /etc/hosts
  become: true
  lineinfile:
    path: "{{ item.file }}"
    regexp: "{{ item.regexp }}"
    state: "{{ item.state }}"
  with_items:
    - { file: "/etc/hosts", regexp: "{{ freeipa.client_server }}", state: absent }
  register: hostname_ipaddr_entries_removed

#
- name: Restart Greenplum Database to apply changes
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  args:
    executable: /bin/bash
  register: gpdb_restarted
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"
