---
gpss_major_version: 1
gpss_minor_version: 9.0
gpss_patch_version:
gpss_gpdb_version: gpdb6
gpss_rhel_version_kafka: rhel7
gpss_rhel_version_gpdb: rhel8
gpss_database_name: testdb
gpss_mdw_hostname: rk8-master
gpss_setup_action: "{{ setup_action }}"
#  gpss-gpdb6-1.6.0-rhel7-x86_64.tar.gz

gpss_port: 50007
gpfdist_port: 8319
gpss_base_dir: /home/gpadmin/gpss-base
gpss_log_dir: /home/gpadmin/gpss-base/logs
gpss_job_name: kafkajson2gp
gpss_install_tar: false

kafka_base_dir: /home/gpadmin/kafka-base
# kafka_major_version: 2
kafka_topic_name: topic-json-gpkafka
kafka_table_name: json_from_kafka
kafka_install_dir: /usr/local/kafka
kafka_replication_factor: 3
kafka_partitions: 3
zookeeper_hosts: "co7-node01:2181,co7-node02:2181,co7-node03:2181"
kafka_broker_hosts: "co7-node01:9092,co7-node02:9092,co7-node03:9092"
print_debug: true

gpss_file_vars:
  - bin/gpkafka
  - bin/gpss
  - bin/gpsscli
  - bin/kafkacat
  - lib/postgresql/gpfmt_gpss.so
  - lib/postgresql/gpfmt_protobuf.so
  - lib/postgresql/gpss.so
  - lib/librdkafka.so
  - lib/librdkafka.so.1
  - lib/libserdes.so
  - lib/libserdes.so.1
  - share/postgresql/extension/dataflow--1.0.sql
  - share/postgresql/extension/dataflow.control
  - share/postgresql/extension/gpss--1.0.sql
  - share/postgresql/extension/gpss.control
  - open_source_license_VMware_Tanzu_Greenplum_Streaming_Server_1.6.0_GA.txt

#  - { id: 2, name: bin/gpss }
#  - { id: 3, name: bin/gpsscli }
#  - { id: 4, name: bin/kafkacat }
#  - { id: 5, name: lib/postgresql/gpfmt_gpss.so }
#  - { id: 6, name: lib/postgresql/gpfmt_protobuf.so }
#  - { id: 7, name: lib/postgresql/gpss.so }
#  - { id: 8, name: lib/librdkafka.so }
#  - { id: 9, name: lib/librdkafka.so.1 }
#  - { id: 10, name: lib/libserdes.so }
#  - { id: 11, name: lib/libserdes.so.1 }
#  - { id: 12, name: share/postgresql/extension/dataflow--1.0.sql }
#  - { id: 13, name: share/postgresql/extension/dataflow.control }
#  - { id: 14, name: share/postgresql/extension/gpss--1.0.sql }
#  - { id: 15, name: share/postgresql/extension/gpss.control }
#  - { id: 16, name: open_source_license_VMware_Tanzu_Greenplum_Streaming_Server_1.6.0_GA.txt }
