###########################################################
# Resource Group configuration
#
# Downloaded From Here - https://pkgs.sysadmins.ws/el9/base/x86_64/
- name: Copy libcgroup RPM Packages for Enabling Cgroup v1
  copy: src={{ item }} dest=/home/gpadmin/{{ item }} mode=0644 owner=gpadmin group=gpadmin
  with_items:
    - libcgroup-devel-3.0-1.el9.0.1.x86_64.rpm
    - libcgroup-pam-3.0-1.el9.0.1.x86_64.rpm
    - libcgroup-3.0-1.el9.0.1.x86_64.rpm
    - libcgroup-tools-3.0-1.el9.0.1.x86_64.rpm
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9


- name: Install libcgroup RPM Packages for Enabling Cgroup v1
  package:
    name: "{{ gpdb.admin_home_dir }}/{{ item }}"
    state: present
    disable_gpg_check: yes
  async: 360
  poll: 5
  with_items:
    - libcgroup-devel-3.0-1.el9.0.1.x86_64.rpm
    - libcgroup-pam-3.0-1.el9.0.1.x86_64.rpm
    - libcgroup-3.0-1.el9.0.1.x86_64.rpm
    - libcgroup-tools-3.0-1.el9.0.1.x86_64.rpm
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9


- name: Create the cgconfig.conf for All Nodes
  template: src=cgconfig.conf.j2 dest=/etc/cgconfig.conf owner=root group=root mode=644 force=yes
  register: cgconfig_created


- name: Copy Systemd Configuration of Cgconfig Into /etc/systemd/system
  template: src=cgconfig.systemd.j2 dest=/etc/systemd/system/cgconfig.service owner=root group=root mode=644 force=yes
  register: systemd_cgconfig_created
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'


- name: Enable and Restart Cgconfig for Applying Config
  systemd:
    name: cgconfig
    enabled: yes
    state: started
    daemon_reload: true
  register: cgconfig_restarted


- name: Enabling Resource Groups by Gpconfig
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpconfig -c gp_resource_manager -v "group" )
  args:
    executable: /bin/bash
  register: resource_group_enabled
  when: inventory_hostname in groups['master']


- name: Apply New Changes for Resource Groups
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  args:
    executable: /bin/bash
  register: rs_applied
  when: inventory_hostname in groups['master']

