---
- name: Verify that Database for DataScienceR is Installed
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ dsr.database_name }}'" )
  args:
    executable: /bin/bash
  register: dsr_database_installed
  when: inventory_hostname in groups['master']


- name: Create Database for DataScienceR
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && createdb {{ dsr.database_name }} )
  args:
    executable: /bin/bash
  register: dsr_database_created
  when: ( inventory_hostname in groups['master'] and '100' not in dsr_database_installed.stdout )


- name: Restart Greenplum Database and Apply Parameters for DataScienceR in greenplum_path.sh
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  args:
    executable: /bin/bash
  async: 60
  poll: 5
  when: inventory_hostname in groups['master']

