---

# Install Keepalived

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'

- name: Installation of Keepalived
  include: install.yml
  tags: install

- name: Uninstallation of Keepalived
  include: uninstall.yml
  tags: uninstall

- name: Upgrade of Keepalived
  include: upgrade.yml
  tags: upgrade
