---
- name: Verify if DataSciencePython Gppkg Package is Installed
  become_user: gpadmin
  shell: ( source {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ check_dspython_installed }} )
  args:
    executable: /bin/bash
  ignore_errors: true
  register: dspython_installed
  changed_when: False
  when: inventory_hostname in groups['master']


- debug: msg={{ dspython_installed.stdout }}
  when: inventory_hostname in groups['master']


- name: Stop if DataSciencePython Gppkg Package is Installed
  fail: msg="DataSciencePython gppkg package is already installed!"
  when: ( inventory_hostname in groups['master'] and 'DataSciencePython' in dspython_installed.stdout )


- name: Copy DataSciencePython Gppkg File
  copy: src={{ dspython_package_name }} dest={{ gpdb.admin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  when: ( inventory_hostname in groups['master'] and 'DataSciencePython' not in dspython_installed.stdout )
- debug: msg={{ dspython_package_name }}


- name: Install DataSciencePython Package
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_install_cmd }} {{ gpdb.admin_home_dir }}/{{ dspython_package_name }} )
  args:
    executable: /bin/bash
  register: dspython_package_installed
  ignore_errors: true
  async: 3600
  poll: 10
  when: ( inventory_hostname in groups['master'] and 'DataSciencePython' not in dspython_installed.stdout )

