---
- name: Verify that Database for DataSciencePython is Installed
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ dspython.database_name }}'" )
  args:
    executable: /bin/bash
  register: dspython_database_installed
  when: inventory_hostname in groups['master']


- name: Create Database for DataSciencePython
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && createdb {{ dspython.database_name }} )
  args:
    executable: /bin/bash
  register: dspython_database_created
  when:
    - inventory_hostname in groups['master']
    - "'100' not in dspython_database_installed.stdout"


- name: Restart Greenplum Database and Apply Parameters for DataSciencePython in greenplum_path.sh
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  args:
    executable: /bin/bash
  async: 150
  poll: 5
  when: inventory_hostname in groups['master']


#- name: The Greenplum Database Python Data Science Modules are installed in the following directory
#  become_user: gpadmin
#  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && ls -al $GPHOME/ext/DataSciencePython/lib/python2.7/site-packages/ )
#  register: dspython_modules_listed

