---
# Uninstall DataSciencePython package on GPDB

#
- name: Check if the GPDB software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed

#
- name: Stop if GPDB software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when: gpdb_installed.stat.exists != True

#
- name: Verify that database for dspython is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ dspython_database_name }}'" )
  register: dspython_database_installed
  when: inventory_hostname in groups['master']

#
- name: Drop database for dspython
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && dropdb {{ dspython_database_name }} )
  register: dspython_database_deleted
  when:
    - inventory_hostname in groups['master']
    - "'100' in dspython_database_installed.stdout"

#
- set_fact:
    gppkg_remove_cmd: "gppkg -r"
    dspython_package_name: DataSciencePython{{ dspython_prefix_major_version }}{{ dspython_major_version }}.{{ dspython_minor_version }}.{{ dspython_patch_version }}
  when: inventory_hostname in groups['master'] and dspython_gpdb_version|int <= 6 and dspython_os_version == "rhel7"
  # when: inventory_hostname in groups['master'] and dspython_gpdb_version|int <= 6 and "{{ dspython_os_version.split('.')[-1]|int }}" == 7

#
- set_fact:
    gppkg_remove_cmd: "gppkg -r"
    dspython_package_name: DataSciencePython{{ dspython_prefix_major_version }}{{ dspython_major_version }}.{{ dspython_minor_version }}-{{ dspython_patch_version }}
  when: inventory_hostname in groups['master'] and dspython_gpdb_version|int <= 6 and dspython_os_version == "rhel8"
  # when: inventory_hostname in groups['master'] and dspython_gpdb_version|int <= 6 and "{{ dspython_os_version.split('.')[-1]|int }}" == 8

#
- set_fact:
    gppkg_remove_cmd: "gppkg -a remove"
    dspython_package_name: DataSciencePython{{ dspython_prefix_major_version }}{{ dspython_major_version }}.{{ dspython_minor_version }}
  when: inventory_hostname in groups['master'] and dspython_gpdb_version|int >= 7 and dspython_os_version == "rhel8"
    # when: inventory_hostname in groups['master'] and dspython_gpdb_version|int >= 7 and "{{ dspython_os_version.split('.')[-1]|int }}" == 8

#
- name: Uninstall the DataSciencePython Package
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_remove_cmd }} {{ dspython_package_name }} )
  register: dspython_package_uninstalled
  async: 3600
  poll: 10
  when:  inventory_hostname in groups['master']

#
- name: Restart the Greenplum Database
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  async: 150
  poll: 5
  when: inventory_hostname in groups['master']
