---

# Uninstall DataSciencePython package on GPDB

- name: Check if the GPDB software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed

- name: Stop if GPDB software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when: gpdb_installed.stat.exists != True

- name: Verify that database for dspython is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ dspython_database_name }}'" )
  register: dspython_database_installed
  when: inventory_hostname in groups['master']

- name: Drop database for dspython
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && dropdb {{ dspython_database_name }} )
  register: dspython_database_deleted
  when:
    - inventory_hostname in groups['master']
    - "'100' in dspython_database_installed.stdout"

- name: Uninstall the DataSciencePython Package
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gppkg -r DataSciencePython-{{ dspython_prefix_major_version }}{{ dspython_major_version }}.{{ dspython_minor_version }}.{{ dspython_patch_version }} )
  register: dspython_extension_uninstalled
  when:
    - inventory_hostname in groups['master']

- name: Restart the Greenplum Database
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  async: 60
  poll: 5
  when:
    - inventory_hostname in groups['master']
