---
# Uninstall DataSciencePython package on GPDB

#
- name: Check if the GPDB software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed

#
- name: Stop if GPDB software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when: gpdb_installed.stat.exists != True

#
- name: Verify that database for dspython is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ dspython.database_name }}'" )
  register: dspython_database_installed
  when: inventory_hostname in groups['master']

#
- name: Drop database for dspython
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && dropdb {{ dspython.database_name }} )
  register: dspython_database_deleted
  when: ( inventory_hostname in groups['master'] and '100' in dspython_database_installed.stdout )

#
- set_fact:
    gppkg_remove_cmd: "gppkg -r"
    check_dspython_installed: "gppkg -q --all | grep DataSciencePython | cut -d - -f 1"
    dspython_package_name: DataSciencePython{{ dspython.prefix_major_version }}{{ dspython.major_version }}.{{ dspython.minor_version }}.{{ dspython.patch_version }}
  when: inventory_hostname in groups['master'] and dspython.gpdb_version|int <= 6 and ( dspython.os_version | regex_replace('[^0-9]','')|int <= 7 )

#
- set_fact:
    gppkg_remove_cmd: "gppkg -r"
    check_dspython_installed: "gppkg -q --all | grep DataSciencePython | cut -d - -f 1"
    dspython_package_name: DataSciencePython{{ dspython.prefix_major_version }}{{ dspython.major_version }}.{{ dspython.minor_version }}-{{ dspython.patch_version }}
  when: inventory_hostname in groups['master'] and dspython.gpdb_version|int <= 6 and ( dspython.os_version | regex_replace('[^0-9]','')|int >= 8 )

#
- set_fact:
    gppkg_remove_cmd: "gppkg -a remove"
    check_dspython_installed: "gppkg query | grep DataSciencePython | awk '{print $1}'"
    dspython_package_name: DataSciencePython{{ dspython.prefix_major_version }}{{ dspython.major_version }}.{{ dspython.minor_version }}
  when: inventory_hostname in groups['master'] and dspython.gpdb_version|int >= 7 and ( dspython.os_version | regex_replace('[^0-9]','')|int >= 8 )

#
- name: Verify if DataSciencePython gppkg is installed
  become_user: gpadmin
  shell: ( source {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && {{ check_dspython_installed }} )
  ignore_errors: true
  register: dspython_installed
  changed_when: False
  when: inventory_hostname in groups['master']

#
- name: Print the result if DataSciencePython is not installed
  debug:
    msg: "{{ dspython_installed.stdout }}"
  when: inventory_hostname in groups['master']

#
- name: Stop if DataSciencePython gppkg package is not installed
  fail: msg="PostGIS gppkg package is not installed!"
  when: ( inventory_hostname in groups['master'] and 'DataSciencePython' not in dspython_installed.stdout )

#
- name: Uninstall the DataSciencePython Package
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_remove_cmd }} {{ dspython_package_name }} )
  register: dspython_package_uninstalled
  async: 3600
  poll: 10
  when:  inventory_hostname in groups['master']

#
- name: Restart the Greenplum Database
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  async: 150
  poll: 5
  when: inventory_hostname in groups['master']

