---
- name: Verify if MetricsCollector GPPKG Pakcage is Installed
  become_user: gpadmin
  shell: ( source {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ check_gpmetrics_installed }} )
  args:
    executable: /bin/bash
  ignore_errors: true
  register: mc_installed
  changed_when: False
  when: inventory_hostname in groups['master']


- name: Stop if MetricsCollector GPPKG Package is Already Installed
  fail: msg="MetricsCollector gppkg package is already installed!"
  when: ( inventory_hostname in groups['master'] and 'MetricsCollector' in mc_installed.stdout )


- name: Install MetricsCollector Extension Package
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_install_cmd }} {{ gpcc_prefix_dir }}/gppkg/{{ gpmetrics_package_name }} )
  args:
    executable: /bin/bash
  ignore_errors: true
  when: ( inventory_hostname in groups['master'] and 'MetricsCollector' not in mc_installed.stdout )


- name: Create MetricsCollector Extension
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -d gpperfmon -c "CREATE EXTENSION metrics_collector;" )
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: mc_extension_created
  when:
    - ( inventory_hostname in groups['master'] and 'MetricsCollector' in mc_installed.stdout )
    - ( gpcc_major_version >= 6 and gpcc_minor_version >= 7 ) or ( gpcc_major_version >= 7 and gpcc_minor_version >= 0 )


- name: Enable the Data Colleciton Agents
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpconfig -c gp_enable_gpperfmon -v on )
  register: gpperfmon_enabled
  when: inventory_hostname in groups['master'] and gpcc.major_version < 7


- name: Enable Query Metrics
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpconfig -c gp_enable_query_metrics -v on )
  register: query_metric_enabled
  when: inventory_hostname in groups['master']


- name: Add GUC of MetricsCollector
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpconfig -c shared_preload_libraries -v 'metrics_collector' )
  register: metrics_collector_added
  when: inventory_hostname in groups['master']


- name: Reload Greenplum Database
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  args:
    executable: /bin/bash
  async: 360
  poll: 5
  when: inventory_hostname in groups['master'] and gpmon_pg_hba_config.changed == True

