---
- name: Verify if MetricsCollector Extension Pakcage is Installed
  become_user: gpadmin
  shell: ( source {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ check_gpmetrics_installed }} )
  args:
    executable: /bin/bash
  ignore_errors: true
  register: mc_installed
  changed_when: False
  when: inventory_hostname in groups['master'] and ( gpcc.major_version >= 6 and gpcc.minor_version >= 7 )


- name: Stop if MetricsCollector Extension Package Is Not Installed
  fail: msg="MetricsCollector extension package is not installed!"
  when: ( gpcc.major_version >= 6 and gpcc.minor_version >= 7 ) and ( inventory_hostname in groups['master'] and 'MetricsCollector' not in mc_installed.stdout )


- name: Drop MetricsCollector Extension
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -d gpperfmon -c "DROP EXTENSION metrics_collector;" )
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: mc_extension_dropped
  when: ( gpcc.major_version >= 6 and gpcc.minor_version <= 7 ) and ( inventory_hostname in groups['master'] and 'MetricsCollector' in mc_installed.stdout )
  # shared_preload_libraries = 'metrics_collector'
  # gp_enable_query_metrics = on


- name: Unnstall MetricsCollector Extension Package
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_remove_cmd }} {{ gpmetrics_package_version }} )
  when: ( gpcc.major_version >= 6 and gpcc.minor_version >= 7 ) and ( inventory_hostname in groups['master'] and 'MetricsCollector' in mc_installed.stdout )

