---
# Install Greenplum Command Center on RedHat / CentOS / Rocky / Ubuntu / Debian

# for now fail if it's not supported OS
- name: Check OS ( GPCC )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

- name: Installation for Red Hat / CentOS / Rocky / Ubuntu / Debian
  include: install.yml
  tags: install

- name: Installation for Red Hat / CentOS / Rocky / Ubuntu / Debian
  include: uninstall.yml
  tags: uninstall
