---
# For Now Fail If It's Not Spported OS
- name: Check OS ( GPCC )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Greenplum Command Center
  import_tasks: set-gpcc-facts.yml
  tags:
    - install
    - uninstall

#- name: Install Greenplum Command Center
#  import_tasks: install.yml
#  tags: install


- name: Add GPMON User
  import_tasks: 01-add-gpmon-user.yml
  tags: install

- name: Create GPPerfmon Agent
  import_tasks: 02-create-gpperfmon-agent.yml
  tags: install

- name: Setup Greenplum Command Center Software
  import_tasks: 03-setup-gpcc-bin.yml
  tags: install

- name: Enable SSL Connection for GPCC Web UI
  import_tasks: 04-enable-ssl.yml
  tags: install

- name: Install Greenplum Command Center Software
  import_tasks: 05-install-gcc.yml
  tags: install

- name: Enable Metric Collector
  import_tasks: 06-enable-metric-collector.yml
  tags: install

- name: Configure Greenplum Command Center
  import_tasks: 07-config-gpcc.yml
  tags: install


- name:  Stop GPCC
  import_tasks: 41-stop-gpcc.yml
  tags: uninstall

- name: Uninstll MetricCollector
  import_tasks: 42-uninstall-metrics-collector.yml
  tags: uninstall

- name: Stop GPCC
  import_tasks: 43-check-stop-gpcc.yml
  tags: uninstall

- name: Disable MetricsCollector
  import_tasks: 44-disable-metrics-collector.yml
  tags: uninstall

- name: Remove GPMon User Role
  import_tasks: 45-remove-gpmon-user-role.yml
  tags: uninstall

- name: Remove GPCC Config
  import_tasks: 46-remove-gpcc-config.yml
  tags: uninstall


#- name: Uninstall Greenplum Command Center
#  import_tasks: uninstall.yml
#  tags: uninstall

