---
#
- name: Add nginx repo
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: >
      http://nginx.org/packages/centos/{{ ansible_distribution_major_version }}/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
  when: nginx_package == 'nginx'

#- name: Add nginx repo
#  yum_repository:
#    name: nginx
#    description: nginx repo
#    baseurl: >
#      http://nginx.org/packages/{{(ansible_distribution == "RedHat") |
#      ternary('rhel', 'centos')}}/{{ ansible_distribution_major_version }}/$basearch/
#    gpgkey: https://nginx.org/keys/nginx_signing.key
#    gpgcheck: yes
#  when: nginx_package == 'nginx'

#
- name: Installing NGINX
  yum: name={{ nginx_package }} validate_certs=no

#
- name: Copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

#
- name: Copy minio app nginx conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  when: nginx_nodes != []
  notify: Restart nginx

#
- name: Show NGINX address
  debug: msg="Minio cluster address http://{{ ansible_default_ipv4.address }}/minio"

#
- name: Starting NGINX
  service:
    name: nginx
    state: started
