---
#
- name: Install firewalld rpm packages
  become: true
  become_user: root
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - firewalld
    - firewalld-filesystem
    - iptables-services

#
- name: Start firewalld for all nodes
  become: true
  become_user: root
  systemd:
    name: firewalld
    state: started
    enabled: yes
  with_items:
    - firewalld
    - iptables

#
#- name: Reset ruleset for public zone in firewalld
#  become: true
#  become_user: root
#  shell: |
#    firewall-cmd --load-zone-defaults=public --permanent
#    firewall-cmd --reload

# Set public as default policy
# $ firewall-cmd --set-default-zone=public
# $ firewall-cmd --reload

#
- name: Utility present
  become: true
  become_user: root
  package:
    name: python3-psycopg2
    state: present
  when: inventory_hostname in groups['master']

#
- name: Get specific tables
  become: true
  become_user: gpadmin
  postgresql_query:
    db: "{{ _dbname }}"
    login_host: "{{ _login_host }}"
    login_user: "{{ _login_user }}"
    login_password: "{{ _login_password }}"
    query: "SELECT hostname, port, address, role FROM gp_segment_configuration;"
    login_unix_socket: /tmp
  register: rs_gp_seg_conf
  when: inventory_hostname in groups['master']

# Test
- name: Set array variable
  set_fact:
    user_array: "{{ rs_gp_seg_conf.query_result }}"
  when: inventory_hostname in groups['master']

#
- name: Print item value # Prints array object as is
  debug:
    msg: "{{ item.hostname }}"
  with_items: "{{ rs_gp_seg_conf.query_result }}"
  when: inventory_hostname in groups['master']

#
- name: Allow tcp ports into corresponding hostname
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    zone: "public"
    port: "{{item.port}}/tcp"
    state: "enabled"
  delegate_to: "{{ item.hostname }}"
  with_items: "{{ rs_gp_seg_conf.query_result }}"
  when: inventory_hostname in groups['master']

#
- name: Allow common ports for all hosts
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/{{ item.proto}}"
    zone: "public"
    state: "enabled"
  with_items: "{{ common_ports }}"

#
- name: Allow ports for master hosts
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/{{ item.proto}}"
    zone: "public"
    state: "enabled"
  with_items: "{{ master_ports }}"
  when: inventory_hostname in groups['master']

#
- name: Allow ports for standby host
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/{{ item.proto}}"
    zone: "public"
    state: "enabled"
  with_items: "{{ standby_ports }}"
  when: inventory_hostname in groups['standby']

#
- name: Allow ports for segments
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/{{ item.proto }}"
    zone: "public"
    state: "enabled"
  with_items: "{{ segment_ports }}"
  when: inventory_hostname in groups['segments']

#
- name: Reload service firewalld to apply new ruleset
  become: true
  become_user: root
  systemd:
    state: reloaded
    name: firewalld
