---

# Install Greenplum Database

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'

- name: Configure firewalld ruleset for gpdb in RHEL or CentOS
  include: install.yml
  tags: install

- name: Remove firewalld ruleset for gpdb in RHEL or CentOS
  include: uninstall.yml
  tags: uninstall
