---
#- name: Stop firewalld for all nodes
#  become: true
#  become_user: root
#  systemd:
#    name: firewalld
#    state: stopped
#    enabled: no
#
#- meta: end_play

#
- name: Get specific tables
  become: true
  become_user: gpadmin
  postgresql_query:
    db: "{{ _dbname }}"
    login_host: "{{ _login_host }}"
    login_user: "{{ _login_user }}"
    login_password: "{{ _login_password }}"
    query: "SELECT hostname, port, address, role FROM gp_segment_configuration;"
    login_unix_socket: /tmp
  register: rs_gp_seg_conf
  when: inventory_hostname in groups['master']

# Test
- name: Set array variable
  set_fact:
    user_array: "{{ rs_gp_seg_conf.query_result }}"
  when: inventory_hostname in groups['master']

#
- name: Print item value # Prints array object as is
  debug:
    msg: "{{ item.hostname }}"
  with_items: "{{ rs_gp_seg_conf.query_result }}"
  when: inventory_hostname in groups['master']

#
- name: Disable port into corresponding hostname
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/tcp"
    state: "disabled"
    zone: "public"
  delegate_to: "{{ item.hostname }}"
  with_items: "{{ rs_gp_seg_conf.query_result }}"
  when: inventory_hostname in groups['master']

#
- name: Disable to allow common ports for all hosts
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/{{ item.proto }}"
    state: "disabled"
    zone: "public"
  with_items: "{{ common_ports }}"

#
- name: Disable to allow ports for master
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/{{ item.proto }}"
    state: "disabled"
    zone: "public"
  with_items: "{{ master_ports }}"
  when: inventory_hostname in groups['master']

#
- name: Disable to allow ports for standby hosts
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/{{ item.proto }}"
    zone: "public"
    state: "disabled"
  with_items: "{{ standby_ports }}"
  when: inventory_hostname in groups['standby']

#
- name: Disable to allow ports for segment hosts
  become: true
  become_user: root
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item.port }}/{{ item.proto }}"
    state: "disabled"
    zone: "public"
  with_items: "{{ segment_ports }}"
  when: inventory_hostname in groups['segments']

#
- name: Reload service firewalld to apply new ruleset
  become: true
  become_user: root
  systemd:
    state: reloaded
    name: "{{ item }}"
  with_items:
    - firewalld
    - iptables

#
- name: Uninstall utility present
  become: true
  package:
    name: python3-psycopg2
    state: absent
  when: inventory_hostname in groups['master']

#
- name: Uninstall firewalld rpm packages
  become: true
  become_user: root
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - firewalld
    - firewalld-filesystem
    - iptables
