---
# Install common role to prepare installing Greenplum Database

#- name: Print OS
#  debug: msg={{ ansible_distribution }}

# for now fail if it's not supported OS
- name: Check OS ( GPDB )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != "RedHat" and ansible_distribution != "CentOS" and ansible_distribution != "Rocky" and ansible_distribution != "Ubuntu" and ansible_distribution != "Debian"

#
- name: Install common role for Red Hat / CentOS / Rocky / Ubuntu / Debian
  include: install.yml
  tags: install

#
- name: Uninstall common role for Red Hat / CentOS / Rocky / Ubuntu / Debian
  include: uninstall.yml
  tags: uninstall
