---
- name: Check OS ( Common )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != "RedHat" and ansible_distribution != "CentOS" and ansible_distribution != "Rocky" and ansible_distribution != "Ubuntu" and ansible_distribution != "Debian"


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Install Common
  import_tasks: install.yml
  tags: install


- name: Uninstall Common
  import_tasks: uninstall.yml
  tags: uninstall

