---
- name: Install Java RPM Package for PXF
  package: name="java-1.8.0" state=present
  when:
    - inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['segments']
    - ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 5


- name: Install Java Dependent Package for PXF
  package: name={{ item }} state=present
  with_items:
    - openssl
    - libssl-dev
    - openjdk-8-jdk
    - openjdk-8-jre
    - openjdk-8-demo
    - openjdk-8-jre-dcevm
    - openjdk-8-jdk-headless
    - openjdk-8-jre-zero
    - openjdk-8-source
    - openjdk-8-jre-headless
    - openjdk-8-dbg
    - openjdk-8-doc
  when:
    - inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['segments']
    - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

