---
# Install PXF for GPDB

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'

#
- name: Install PXF
  import_tasks: install.yml
  tags: install
  when: install_pxf == true

#
- name: Setup NFS Access
  import_tasks: setup-nfs-access.yml
  tags: install
  when: with_nfs_access == true

#
- name: Setup HDFS Access
  import_tasks: setup-hadoop-access.yml
  tags: install
  when: with_hadoop_access == true

#
- name: Setup Oracle Access
  import_tasks: setup-oracle-access.yml
  tags: install
  when: with_oracle_access == true

#
- name: Setup MS-SQL Access
  import_tasks: setup-mssql-access.yml
  tags: install
  when: with_mssql_access == true

#
- name: Setup Minio Access
  import_tasks: setup-minio-access.yml
  tags: install
  when: with_minio_access == true

#
- name: Uninstall PXF
  import_tasks: uninstall.yml
  tags: uninstall

#
- name: Upgrade PXF
  import_tasks: upgrade.yml
  tags: upgrade.yml

