---
# Install PXF for GPDB

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'

- name: Install PXF
  include: install.yml
  tags: install

- name: Setup HDFS Access
  include: setup-hadoop-access.yml
  tags: install
  when: with_hadoop_access == true

- name: Test HDFS Access
  include: test-pxf-hadoop-data.yml
  tags: install
  when: with_hadoop_access == true

- name: Uninstall PXF
  include: uninstall.yml
  tags: uninstall

- name: Upgrade PXF
  include: upgrade.yml
  tags: upgrade.yml
