---
# Uninstall PXF on GPDB for Red Hat
#
- name: Check if the PXF cluster is runnong on each segment host for MSSQL
  become_user: "{{ gpdb.admin_user }}"
  shell: ( source ~/.bashrc && PXF_BASE={{ mssql.base_work_dir }} pxf cluster status )
  ignore_errors: yes
  register: pxf_running_checked
  when: inventory_hostname in groups['master'] and mssql.access == true

#
- name: Stop pxf cluster runnong on each segment host for MSSQL
  become_user: "{{ gpdb.admin_user }}"
  shell: ( source ~/.bashrc && export PXF_BASE={{ mssql.base_work_dir }} && pxf cluster stop )
  ignore_errors: yes
  when:
    - inventory_hostname in groups['master'] and 'PXF is running on' in pxf_running_checked_nfs.stdout
    - mssql.access == true

#
- name: Delete PXF Base directory and query examples directory for NFS Access
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ mssql.base_work_dir }}"
  when: mssql.access == true

