---
#
- name: Check if the pxf cluster is runnong on each segment host for MinIO
  become_user: "{{ gpdb.user }}"
  shell: ( source ~/.bashrc && PXF_BASE={{ minio.base_work_dir }} pxf cluster status )
  ignore_errors: yes
  register: pxf_running_checked_minio
  when: minio.access == true and inventory_hostname in groups['master']

#
- name: Stop pxf cluster runnong on each segment host for MinIO
  become_user: "{{ gpdb.user }}"
  shell: ( source ~/.bashrc && PXF_BASE={{ minio.base_work_dir }} pxf cluster stop )
  ignore_errors: yes
  when:
    - minio.access == true and inventory_hostname in groups['master']
    - "'PXF is running on' in pxf_running_checked_minio.stdout"

#
- name: Delete PXF Base directory and query examples directory for MinIO
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ minio.base_work_dir }}"
  when: minio.access == true and inventory_hostname in groups['master']
