---

# Ungrade Greenplum Database on Red Hat / CentOS

- name: Detect Google Cloud
  stat: path=/etc/yum.repos.d/google-cloud.repo
  register: google_cloud_detect

- name: Register Google Cloud
  set_fact:
    google_cloud: true
  when: google_cloud_detect.stat.exists

- name: Check if any version of Greenplum Database is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed

- name: Check if the Greenplum Database version is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db-{{ gpdb_major_version }}.{{ gpdb_minor_version }}
  register: gpdb_version_installed

- name: Sanity check for {{ gpdb_base_dir }}/greenplum-db
  fail: msg="{{ gpdb_base_dir }}/greenplum-db is supposed to be a symlink!"
  when: gpdb_installed.stat.exists == True and gpdb_installed.stat.islnk != True

- name: Shutdown database
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -a )
  async: 60
  poll: 5
  when:
   - inventory_hostname in groups['master']
   - gpdb_installed.stat.exists == True and gpdb_version_installed.stat.exists == True

- name: Copy Greenplum Database {{ gpdb_major_version }} {{ gpdb_binary_type }} file
  copy: src={{ binary_installer_file }}.rpm dest=/home/gpadmin/{{ binary_installer_file }}.rpm mode=0644 owner=gpadmin group=gpadmin
  when:
    - gpdb_binary_type == 'rpm'

- name: Upgrade Greenplum Database software in {{ gpdb_base_dir }}
  yum:
    name: /home/gpadmin/{{ binary_installer_file }}.rpm
    state: latest
  async: 60
  poll: 5
  when:
    - gpdb_installed.stat.exists == True and gpdb_version_installed.stat.exists == True
    - gpdb_binary_type == 'rpm'

- name: Update the permissions for the new installation
  become_user: gpadmin
  file:
    path: "{{ gpdb_base_dir }}/greenplum-db-{{ gpdb_major_version }}.{{ gpdb_minor_version }}.{{ gpdb_build_version }}"
    owner: gpadmin
    group: gpadmin
    recurse: yes

- name: Change the following line in the .bashrc or your chosen profile file
  replace:
    path: /home/gpadmin/.bashrc
    regexp: "^source /usr/local/greenplum-db*"
    replace: "^source {{ gpdb_base_dir }}/greenplum-db-{{ gpdb_major_version }}.{{ gpdb_minor_version }}.{{ gpdb_build_version }}"
    backup: yes
# GPHOME=/usr/local/greenplum-db-6.11.1 in /usr/local/greenplum-db/greenplum_path.sh

- name: Remove the link to point to the earily installed version
  become_user: gpadmin
  file:
    path: "{{ gpdb_base_dir }}/greenplum-db"
    owner: gpadmin
    group: gpadmin
    state: absent

- name: Update the link to point to the newly installed version
  file:
    src: "{{ gpdb_base_dir }}/greenplum-db-{{ gpdb_major_version }}.{{ gpdb_minor_version }}.{{ gpdb_build_version }}"
    dest: "{{ gpdb_base_dir }}/greenplum-db"
    state: link

- name: Source the environment file of GPDB
  become_user: gpadmin
  changed_when: False
  shell: ( source /home/gpadmin/.bashrc )
  register: environment_sourced
  when: inventory_hostname in groups['master']

- name: Start Greenplum Database after upgrade
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstart -a )
  async: 60
  poll: 5
  when:
    - inventory_hostname in groups['master']
