---
# number of Greenplum Database segments
local_machine_user: "moonja"
gpdb_number_segments: 4
gpdb_mirror_enable: true
gpdb_spread_mirrors: ""

gpdb_base_dir: "/usr/local"
gpdb_data_dir: "/data"

# greenplum-db-7.0.0-el8-x86_64.rpm
# greenplum-db-7.0.0-beta.4-el8-x86_64.rpm
# greenplum-db-6.24.3-ubuntu18.04-amd64.deb
gpdb_major_version: 7
gpdb_minor_version: 0.0
gpdb_build_version:
gpdb_os_name: 'el8'
gpdb_arch_name: 'x86_64'
gpdb_binary_type: 'rpm'
# gpdb_os_name: 'ubuntu18.04'
# gpdb_arch_name: 'amd64'
# gpdb_binary_type: 'deb'

smdw_hostname: "rk8-slave"
# smdw_hostname: "rk8-slave"
# smdw_hostname: "co7-slave"

seg_serialized_install: False
gpdb_initdb_single: False
gpdb_initdb_with_standby: True
gpdb_network_range: "192.168.0.0"
gpdb_admin_password: "changeme"
master_data_dir: "/data/master/gpseg-1"

common_gpdb_kernel_parameters:
  - { "state": "present",  "param" : "kernel.shmmax",                             "value" : "500000000" }
  - { "state": "present",  "param" : "kernel.shmmni",                             "value" : "4096" }
  - { "state": "present",  "param" : "kernel.shmall",                             "value" : "4000000000" }
  - { "state": "present",  "param" : "kernel.sem",                                "value" : "250 512000 100 2048" }
  - { "state": "present",  "param" : "kernel.msgmnb",                             "value" : "65536" }
  - { "state": "present",  "param" : "kernel.msgmax",                             "value" : "65536" }
  - { "state": "present",  "param" : "kernel.msgmni",                             "value" : "2048" }
  - { "state": "present",  "param" : "kernel.sysrq",                              "value" : "1" }
  - { "state": "present",  "param" : "kernel.core_uses_pid",                      "value" : "1" }
  - { "state": "present",  "param" : "net.core.rmem_max",                         "value" : "2097152" }
  - { "state": "present",  "param" : "net.core.wmem_max",                         "value" : "2097152" }
  - { "state": "present",  "param" : "vm.overcommit_memory",                      "value" : "2" }
  - { "state": "present",  "param" : "net.ipv4.ip_forward",                       "value" : "0" }
  - { "state": "present",  "param" : "net.ipv4.tcp_syncookies",                   "value" : "1" }
  - { "state": "present",  "param" : "net.core.netdev_max_backlog",               "value" : "10000" }
  - { "state": "present",  "param" : "net.ipv4.tcp_max_syn_backlog",              "value" : "4096" }
  - { "state": "present",  "param" : "net.ipv4.conf.all.arp_filter",              "value" : "1" }
  - { "state": "present",  "param" : "net.ipv6.conf.all.disable_ipv6",            "value" : "0" }
  - { "state": "present",  "param" : "net.ipv4.conf.default.accept_source_route", "value" : "0" }
  - { "state": "present",  "param" : "net.ipv4.ip_local_port_range",              "value" : "10000    65535" }
  - { "state": "present",  "param" : "net.ipv4.conf.all.arp_filter",              "value" : "1" }
  - { "state": "present",  "param" : "net.core.netdev_max_backlog",               "value" : "10000" }
  - { "state": "present",  "param" : "vm.swappiness",                             "value" : "10" }
  - { "state": "present",  "param" : "vm.zone_reclaim_mode",                      "value" : "0" }
  - { "state": "present",  "param" : "vm.dirty_expire_centisecs",                 "value" : "500" }
  - { "state": "present",  "param" : "vm.dirty_writeback_centisecs",              "value" : "100" }
  - { "state": "present",  "param" : "vm.dirty_background_ratio",                 "value" : "0" }
  - { "state": "present",  "param" : "vm.dirty_ratio",                            "value" : "0" }
  - { "state": "present",  "param" : "vm.dirty_background_bytes",                 "value" : "1610612736" }
  - { "state": "present",  "param" : "vm.dirty_bytes",                            "value" : "4294967296" }
  - { "state": "present",  "param" : "vm.overcommit_ratio",                       "value" : "95" }

rhel7_gpdb_kernel_parameters:
  - { "state": "present",  "param" : "net.ipv4.tcp_tw_recycle",                   "value" : "1" }

enable_ssl: true
# SSL Key configuration
gpdb_ssl_dir: "{{ master_data_dir }}"
gpdb_ssl_days: 3660
gpdb_ssl_country: "KR"
gpdb_ssl_state: "Seoul"
gpdb_ssl_location: "GangNam"
gpdb_ssl_organization: "Pivotal"
gpdb_ssl_common_name: "jtest.pivotal.io"
gpdb_ssl_email: "jomoon@pivotal.io"
