pgbouncer_users:
  - name: testuser
    pass: changeme
  - name: postgres
    pass: changeme
    # host: changeme

pgbouncer_databases:
  - name: "db1"
    host: "{{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}"
    port: 5432

pgbouncer_max_client_conn: 300
pgbouncer_max_db_connections: 300
pgbouncer_max_user_connections: 300

# govern how many backend connections
pgbouncer_default_pool_size: 80

monit_protection: true
collectd_monitoring: true
