---
- name: Restart minio service
  systemd: name={{ minio_service }} state=restarted daemon_reload=yes
  listen: restart minio

- name: Wait until minio started
  wait_for:
    host: "{{ ansible_default_ipv4.address | default('localhost') }}"
    port: "{{ minio_port }}"
    delay: 10
  listen: restart minio

- name: Restart nginx
  service: name=nginx state=restarted

- name: Systemd daemon-reload
  systemd: daemon_reload=yes
