---
- name: Check OS ( GPText )
  fail: msg="Not a Red Hat based system!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Apply Facts for All Hosts
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Install GPText
  import_tasks: install.yml
  tags: install


- name: Uninstall GPText
  import_tasks: uninstall.yml
  tags: uninstall

