---
# Install Greenplum Command Text
#
# for now fail if it's not a Red Hat based system
- name: Check OS (PGCC v2)
  fail: msg="Not a Red Hat based system!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Apply facts of all nodes during deploy or destroy GPText
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall

#
- name: Install GPText
  import_tasks: install.yml
  tags: install

#
- name: Uninstall GPText
  import_tasks: uninstall.yml
  tags: uninstall

