---

# Install Greenplum Command Center v1

# for now fail if it's not a Red Hat based system
- name: Check OS (PGCC v2)
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'

- name: Installation for Red Hat / CentOS
  include: gptext-install.yml
  tags: install

- name: Installation for Red Hat / CentOS
  include: gptext-uninstall.yml
  tags: uninstall
