---
- name: Check if SSL Directory Already Exists
  stat: path={{ ssl.dir }}
  register: check_dir_sslkey_installed
  when: ( inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] ) and enable_ssl == True


- name: Create SSL Directory
  file: path={{ ssl.dir }} state=directory owner=gpadmin group=gpadmin
  changed_when: False
  register: dir_sslkey_installed
  when: ( inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] ) and ( check_dir_sslkey_installed.stat.exists != True and enable_ssl == True )


- name: Create SSL Key to Connect into Greenplum MPP Database
  shell: ( openssl req -newkey rsa:2048 -x509 -keyout {{ ssl.dir }}/cert.pem -new -text -out {{ ssl.dir }}/server.req -days {{ ssl.days }} -nodes -subj "/C={{ ssl.country }}/ST={{ ssl.state }}/L={{ ssl.location }}/O={{ ssl.organization }}/CN={{ ssl.common_name }}/emailAddress={{ ssl.email }}" )
  args:
    executable: /bin/bash
  when: ( inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] ) and enable_ssl == True


- name: xxxxx
  shell: ( openssl rsa -in {{ ssl.dir }}/cert.pem -out {{ ssl.dir }}/server.key )
  args:
    executable: /bin/bash
  when: ( inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] ) and enable_ssl == True


- name: Turn the certificate into a self-signed certificate so that the server will look for them.
  shell: ( openssl req -x509 -in {{ ssl.dir }}/server.req -key {{ ssl.dir }}/server.key -new -text -out {{ ssl.dir }}/server.crt -days {{ ssl.days }} -nodes -subj "/C={{ ssl.country }}/ST={{ ssl.state }}/L={{ ssl.location }}/O={{ ssl.organization }}/CN={{ ssl.common_name }}/emailAddress={{ ssl.email }}" )
  args:
    executable: /bin/bash
  when: ( inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] ) and enable_ssl == True


- name: Change Permission of SSL Key Files to Login Greenplum MPP Database via SSL
  file:
    path: "{{ ssl.dir }}/{{ item }}"
    state: file
    owner: gpadmin
    group: gpadmin
    mode: "0600"
  with_items:
    - "server.key"
    - "server.crt"
    - "server.req"
    - "cert.pem"
  when: ( inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] )


- name: Add SSL Configuration File to Authenticate SSL User into Greenplum MPP Database
  lineinfile:
    dest: "{{ gpdb.master_data_dir }}/{{ item.file }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { file: "pg_hba.conf",     line: "hostssl  all         all           0.0.0.0/0         md5",           state: present }
    - { file: "postgresql.conf", line: "ssl = on",           state: present }
  register: ssl_postgres_config
  when:
    - ( inventory_hostname in groups['master'] and enable_ssl == True and gpdb.initdb_with_standby == True ) or ( inventory_hostname in groups['standby'] and gpdb.initdb_with_standby == True and enable_ssl == True )

