---
- name: Verify if PL/R Gppkg Pakcage is Installed
  become_user: gpadmin
  shell: ( source {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ check_plr_installed }} )
  args:
    executable: /bin/bash
  ignore_errors: true
  register: plr_installed
  changed_when: False
  when: inventory_hostname in groups['master']


- name: Stop if PL/R Gppkg Package is Already Installed
  fail: msg="PLR gppkg package is already installed!"
  when: ( inventory_hostname in groups['master'] and 'plr' in plr_installed.stdout )


- name: Copy PL/R Gppkg Pakcage File
  copy: src={{ plr_package_name }} dest={{ gpdb.admin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  when: ( inventory_hostname in groups['master'] and 'plr' not in plr_installed.stdout )


- name: Install PL/R Gppkg Package
  become_user: gpadmin
  shell: ( source {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_install_cmd }} {{ gpdb.admin_home_dir }}/{{ plr_package_name }} )
  args:
    executable: /bin/bash
  register: plr_package_installed
  ignore_errors: true
  until: plr_package_installed is succeeded
  retries: 5
  delay: 10
  when: ( inventory_hostname in groups['master'] and 'plr' not in plr_installed.stdout )
# async: 600
# poll: 5


- name: Restart Greenplum Database and Apply Parameters for PL/R in greenplum_path.sh
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  args:
    executable: /bin/bash
  async: 60
  poll: 5
  when: inventory_hostname in groups['master']


- name: Verify that Database for PL/R is Installed
  become_user: gpadmin
  shell: ( . {{ gpdb.base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ plr.database_name }}'" )
  args:
    executable: /bin/bash
  register: plr_database_installed
  when: inventory_hostname in groups['master']

