---

# Install plr extention on Greenplum database

- name: Check if the GPDB software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed

- name: Stop if GPDB software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when: gpdb_installed.stat.exists != True

- name: Verify that database is up and running
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -c "SELECT VERSION()" )
  args:
    executable: /bin/bash
  register: select_version
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

#
- name: Verify if PLR gppkg package is installed
  become_user: gpadmin
  command: 'rpm -q plr --dbpath /usr/local/greenplum-db/share/packages/database'
  ignore_errors: true
  register: plr_installed
  changed_when: False
  when: inventory_hostname in groups['master'] and ( plr_major_version <= 3 and plr_minor_version < 1 )

#
- name: Verify if PLR gppkg pakcage is installed
  become_user: gpadmin
  shell: ( source {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gppkg query | grep plr | awk '{print $1}' ) 
  args:
    executable: /bin/bash
  ignore_errors: true
  register: plr_installed
  changed_when: False
  when: inventory_hostname in groups['master'] and ( plr_major_version >= 3 and plr_minor_version >= 1 )

#
- name: Stop if PLR gppkg package is not installed
  fail: msg="PLR gppkg package is already installed!"
  when:
    - inventory_hostname in groups['master'] and ( plr_major_version <= 3 and plr_minor_version < 1 )
    - "'package plr is not installed' not in plr_installed.stdout"

- name: Stop if PLR gppkg package is already installed
  fail: msg="plr gppkg package is already installed!"
  when:
    - inventory_hostname in groups['master'] and ( plr_major_version >= 3 and plr_minor_version >= 1 )
    - "'plr' in plr_installed.stdout"

- set_fact:
    gppkg_install_cmd: "gppkg -i"
    plr_package_name: plr-{{ plr_prefix_major_version }}{{ plr_major_version }}.{{ plr_minor_version }}.{{ plr_patch_version }}-{{ plr_gpdb_version }}-{{ plr_os_version }}-{{ plr_arch_type }}.gppkg
  when: inventory_hostname in groups['master'] and ( plr_major_version <= 3 and plr_minor_version < 1 )

#
- set_fact:
    gppkg_install_cmd: "gppkg -a install"
    plr_package_name: plr-{{ plr_major_version }}.{{ plr_minor_version }}.{{ plr_patch_version }}-{{ plr_gpdb_version }}-{{ plr_os_version }}-{{ plr_arch_type }}.gppkg
  when: inventory_hostname in groups['master'] and ( plr_major_version >= 3 and plr_minor_version >= 1 )

#
- name: Copy PLR gppkg pakcage file
  copy: src={{ plr_package_name }} dest={{ gpadmin_home_dir }} mode=0644 owner=gpadmin group=gpadmin
  when:
    - inventory_hostname in groups['master']
    - ( 'package plr is not installed' in plr_installed.stdout ) or ( 'plr' not in plr_installed.stdout )

#
- name: Install PLR gppkg package
  become_user: gpadmin
  shell: ( source {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && {{ gppkg_install_cmd }} {{ gpadmin_home_dir }}/{{ plr_package_name }} )
  args:
    executable: /bin/bash
  register: plr_package_installed
  ignore_errors: true
  async: 300
  poll: 30
  until: plr_package_installed is succeeded
  retries: 3
  delay: 20
  when:
    - inventory_hostname in groups['master']
    - ( 'package plr is not installed' in plr_installed.stdout ) or ( 'plr' not in plr_installed.stdout )

#
- name: Restart GPDB and apply parameters for plr in greenplum_path.sh
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  args:
    executable: /bin/bash
  async: 60
  poll: 5
  when:
    - inventory_hostname in groups['master']

- name: Verify that database for plr is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ plr_database_name }}'" )
  args:
    executable: /bin/bash
  register: plr_database_installed
  when: inventory_hostname in groups['master']

- name: Create database for plr
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && createdb {{ plr_database_name }} )
  args:
    executable: /bin/bash
  register: plr_database_created
  when:
    - inventory_hostname in groups['master']
    - "'100' not in plr_database_installed.stdout"

- name: Enabling PL/R Language Support for GPDB 4.x
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && createlang plr -d {{ plr_database_name }} )
  args:
    executable: /bin/bash
  register: plr_language_support_enabled
  when:
    - inventory_hostname in groups['master']
    - plr_gpdb_version == "GPDB4.3"
    - "'100' not in plr_database_installed.stdout"

- name: Enabling PL/R Language Support for GPDB 6.x or 7.x
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -d {{ plr_database_name }} -c "CREATE EXTENSION plr;" )
  args:
    executable: /bin/bash
  register: plr_language_support_enabled
  when:
    - inventory_hostname in groups['master']
    - plr_gpdb_version == "gpdb6" or plr_gpdb_version == "gp6" or plr_gpdb_version == "gp7"
    - "'100' not in plr_database_installed.stdout"
