---
- name: Check OS ( PL/R )
  fail: msg="Not a Red Hat based system!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for PL/R
  import_tasks: set-plr-facts.yml
  tags:
    - install
    - uninstall


- name: Check if Greenplum Database is Installed and Running
  import_tasks: 01-check-gpdb.yml
  tags: install


- name: Install PL/R
  import_tasks: 02-install-plr.yml
  tags: install


- name: Configure PL/R
  import_tasks: 03-config-plr.yml
  tags: install


- name: Check if Greenplum Database is Installed and Running
  import_tasks: 41-check-gpdb.yml
  tags: uninstall


- name: Remove Pl/R Extensions and Database
  import_tasks: 42-remove-plr-extension.yml
  tags: uninstall


- name: Remove PL/R Packages and Restart Greenplum Database
  import_tasks: 43-remove-plr-pkgs.yml
  tags: uninstall

