---

# Install plpython extention on Greenplum database

- name: Check if the GPDB software is already installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed

- name: Stop if GPDB software is not installed
  fail: msg="Greenplum Database software is not installed!"
  when: gpdb_installed.stat.exists != True

- name: Verify that database is up and running
  become_user: gpadmin
  changed_when: False
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -c "SELECT VERSION()" )
  register: select_version
  when: inventory_hostname in groups['master']
  failed_when: "'(Greenplum Database ' not in select_version.stdout"

- name: Restart GPDB and apply parameters for plpython in greenplum_path.sh
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  async: 60
  poll: 5
  when:
    - inventory_hostname in groups['master']

- name: Verify that database for plpython is installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ plpython_database_name }}'" )
  register: plpython_database_installed
  when: inventory_hostname in groups['master']

- name: Create database for plpython
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && createdb {{ plpython_database_name }} )
  register: plpython_database_created
  when:
    - inventory_hostname in groups['master']
    - "'100' not in plpython_database_installed.stdout"

- name: Enabling PL/Python Language Support for GPDB 6.x
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -d {{ plpython_database_name }} -c "CREATE EXTENSION plpythonu;" )
  register: plpython_language_support_enabled
  when:
    - inventory_hostname in groups['master']
    - plpython_gpdb_version == "gp6"
    - "'100' not in plpython_database_installed.stdout"
