---
- name: Check OS ( PL/Python )
  fail: msg="Not a Red Hat based system!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Install PL/Python
  import_tasks: install.yml
  tags: install


- name: Uninstall PL/Python
  import_tasks: uninstall.yml
  tags: uninstall

