---
- name: Check if the Greenplum Database Software is Already Installed
  stat: path={{ gpdb_base_dir }}/greenplum-db
  register: gpdb_installed


- name: Stop if Greenplum Database Software is Not Installed
  fail: msg="Greenplum Database software is not installed!"
  when: gpdb_installed.stat.exists != True


- name: Verify that Database for PL/Perl is Installed
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && psql -tAc "SELECT 100 FROM pg_database WHERE datname='{{ plperl.database_name }}'" )
  register: plperl_database_installed
  when: inventory_hostname in groups['master']


- name: Drop a Database for PL/Perl
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && dropdb {{ plperl.database_name }} )
  register: plperl_database_deleted
  when:
    - inventory_hostname in groups['master']
    - "'100' in plperl_database_installed.stdout"


- name: Restart the Greenplum Database
  become_user: gpadmin
  shell: ( . {{ gpdb_base_dir }}/greenplum-db/greenplum_path.sh && gpstop -ra )
  async: 60
  poll: 5
  when: inventory_hostname in groups['master']

