#!/bin/bash

  if [[ $1 == "--help" ]]; then
    echo "Make sure GPHOME environment variable is set, then run this file to install GPSS"
    exit 0
  fi
  if [[ -z "${GPHOME}" ]]; then
    echo "Error: Environment Variable GPHOME not set!!"
    exit 1
  fi

  cp -av bin lib share $GPHOME
  if [ $? -eq 0 ]; then
    echo "Install Done"
  fi

